var _yt_www={};(function(g){var window=this;var baa,caa,Ba,Ea,db,kaa,eb,fb,gb,hb,mb,laa,nb,maa,xb,naa,ub,Gb,Xb,$b,dc,fc,Sc,waa,yaa,xaa,zaa,Aaa,fd,id,sd,xd,Eaa,Faa,Daa,Gaa,be,de,ce,Jaa,Kaa,Laa,Maa,Naa,he,ne,pe,Paa,qe,re,te,Qaa,xe,je,ue,we,fe,ee,ge,le,oe,ye,Ke,Ne,Qe,Se,Ye,Ze,uf,vf,Waa,Df,Ef,Xaa,Hf,Lf,Jf,If,Yaa,Of,Pf,Sf,Uf,Vf,Wf,Zf,Yf,ag,Xf,bg,Qf,Tf,dba,cg,dg,eba,fba,jg,lg,ng,ug,gba,zg,xg,iba,Cg,Ag,Bg,Gg,hba,Eg,lba,kba,jba,Kg,Jg,Lg,Ng,mba,nba,Og,Pg,Ug,Yg,Zg,$g,ch,dh,eh,tba,uba,Vg,Xg,Tg,sba,Wg,hh,ih,oa,aaa;
g.ba=function(a){return function(){return g.aa[a].apply(this,arguments)}};
g.ca=function(a){return void 0!==a};
g.m=function(a,b,c){a=a.split(".");c=c||g.da;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&g.ca(b)?c[d]=b:c[d]?c=c[d]:c=c[d]={}};
g.p=function(a,b){for(var c=a.split("."),d=b||g.da,e;e=c.shift();)if(null!=d[e])d=d[e];else return null;return d};
g.ea=function(){};
g.fa=function(a){a.getInstance=function(){return a.uc?a.uc:a.uc=new a}};
g.ga=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};
g.ha=function(a){return"array"==g.ga(a)};
g.ia=function(a){var b=g.ga(a);return"array"==b||"object"==b&&"number"==typeof a.length};
g.ja=function(a){return"string"==typeof a};
g.ka=function(a){return"number"==typeof a};
g.ma=function(a){return"function"==g.ga(a)};
g.na=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};
g.pa=function(a){return a[oa]||(a[oa]=++aaa)};
baa=function(a,b,c){return a.call.apply(a.bind,arguments)};
caa=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};
g.q=function(a,b,c){g.q=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?baa:caa;return g.q.apply(null,arguments)};
g.r=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};
g.u=function(a,b){function c(){}
c.prototype=b.prototype;a.K=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.jU=function(a,c,f){for(var k=Array(arguments.length-2),l=2;l<arguments.length;l++)k[l-2]=arguments[l];return b.prototype[c].apply(a,k)}};
g.qa=function(a){g.qa[" "](a);return a};
g.ra=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,g.ra);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};
g.sa=function(a,b){return 0==a.lastIndexOf(b,0)};
g.ta=function(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c};
g.ua=function(a){return(0,window.encodeURIComponent)(String(a))};
g.va=function(a){return(0,window.decodeURIComponent)(a.replace(/\+/g," "))};
g.xa=function(a){if(!daa.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(eaa,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(faa,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(gaa,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(haa,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(iaa,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(jaa,"&#0;"));return a};
g.ya=function(a,b){return-1!=a.indexOf(b)};
g.za=function(a){return String(a).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08")};
g.Ca=function(a,b){for(var c=0,d=(0,g.Aa)(String(a)).split("."),e=(0,g.Aa)(String(b)).split("."),f=Math.max(d.length,e.length),k=0;0==c&&k<f;k++){var l=d[k]||"",n=e[k]||"",t=RegExp("(\\d*)(\\D*)","g"),w=RegExp("(\\d*)(\\D*)","g");do{var H=t.exec(l)||["","",""],R=w.exec(n)||["","",""];if(0==H[0].length&&0==R[0].length)break;c=Ba(0==H[1].length?0:(0,window.parseInt)(H[1],10),0==R[1].length?0:(0,window.parseInt)(R[1],10))||Ba(0==H[2].length,0==R[2].length)||Ba(H[2],R[2])}while(0==c)}return c};
Ba=function(a,b){return a<b?-1:a>b?1:0};
g.Da=function(a){for(var b=0,c=0;c<a.length;++c)b=31*b+a.charCodeAt(c)>>>0;return b};
Ea=function(a){return String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()})};
g.Fa=function(a){var b=g.ja(void 0)?g.za(void 0):"\\s";return a.replace(new RegExp("(^"+(b?"|["+b+"]+":"")+")([a-z])","g"),function(a,b,e){return b+e.toUpperCase()})};
g.Ia=function(a,b,c){b=g.Ha(a,b,c);return 0>b?null:g.ja(a)?a.charAt(b):a[b]};
g.Ha=function(a,b,c){for(var d=a.length,e=g.ja(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return f;return-1};
g.Ka=function(a,b){return 0<=(0,g.Ja)(a,b)};
g.Ma=function(a,b){var c=(0,g.Ja)(a,b),d;(d=0<=c)&&g.La(a,c);return d};
g.La=function(a,b){return 1==Array.prototype.splice.call(a,b,1).length};
g.Na=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};
g.Oa=function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(g.ia(d)){var e=a.length||0,f=d.length||0;a.length=e+f;for(var k=0;k<f;k++)a[e+k]=d[k]}else a.push(d)}};
g.Pa=function(a){return function(){return a}};
g.Qa=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}};
g.Ra=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};
g.Sa=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};
g.Ta=function(a,b,c){for(var d in a)if(b.call(c,a[d],d,a))return d};
g.Ua=function(a){for(var b in a)return!1;return!0};
g.Va=function(a,b){b in a&&delete a[b]};
g.Wa=function(a,b,c){if(null!==a&&b in a)throw Error('The object already contains the key "'+b+'"');a[b]=c};
g.Xa=function(a){var b={},c;for(c in a)b[c]=a[c];return b};
g.Za=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Ya.length;f++)c=Ya[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};
g.ab=function(a){return g.ya(g.$a,a)};
g.bb=function(){return g.ab("Trident")||g.ab("MSIE")};
g.cb=function(){return(g.ab("Chrome")||g.ab("CriOS"))&&!g.ab("Edge")};
db=function(a){g.da.setTimeout(function(){throw a;},0)};
kaa=function(){var a=g.da.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!g.ab("Presto")&&(a=function(){var a=window.document.createElement("IFRAME");a.style.display="none";a.src="";window.document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host,a=(0,g.q)(function(a){if(("*"==
d||a.origin==d)&&a.data==c)this.port1.onmessage()},this);
b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});
if("undefined"!==typeof a&&!g.bb()){var b=new a,c={},d=c;b.port1.onmessage=function(){if(g.ca(c.next)){c=c.next;var a=c.Bp;c.Bp=null;a()}};
return function(a){d.next={Bp:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof window.document&&"onreadystatechange"in window.document.createElement("SCRIPT")?function(a){var b=window.document.createElement("SCRIPT");
b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};
window.document.documentElement.appendChild(b)}:function(a){g.da.setTimeout(a,0)}};
eb=function(a,b,c){this.F=c;this.B=a;this.D=b;this.C=0;this.A=null};
fb=function(a,b){a.D(b);a.C<a.F&&(a.C++,b.next=a.A,a.A=b)};
gb=function(){this.C=this.A=null};
hb=function(){this.next=this.scope=this.oe=null};
mb=function(a,b){ib||laa();jb||(ib(),jb=!0);var c=kb,d=lb.get();d.set(a,b);c.C?c.C.next=d:c.A=d;c.C=d};
laa=function(){if(g.da.Promise&&g.da.Promise.resolve){var a=g.da.Promise.resolve(void 0);ib=function(){a.then(nb)}}else ib=function(){var a=nb;
!g.ma(g.da.setImmediate)||g.da.Window&&g.da.Window.prototype&&!g.ab("Edge")&&g.da.Window.prototype.setImmediate==g.da.setImmediate?(ob||(ob=kaa()),ob(a)):g.da.setImmediate(a)}};
nb=function(){for(var a=null;a=kb.remove();){try{a.oe.call(a.scope)}catch(b){db(b)}fb(lb,a)}jb=!1};
g.pb=function(){this.Md=this.Md;this.Kb=this.Kb};
g.sb=function(a,b){g.qb(a,g.r(g.rb,b))};
g.qb=function(a,b){a.Md?b.call(void 0):(a.Kb||(a.Kb=[]),a.Kb.push(g.ca(void 0)?(0,g.q)(b,void 0):b))};
g.rb=function(a){a&&"function"==typeof a.dispose&&a.dispose()};
g.tb=function(a){g.pb.call(this);this.D=1;this.C=[];this.B=0;this.A=[];this.sd={};this.F=!!a};
maa=function(a,b,c){mb(function(){a.apply(b,c)})};
g.wb=function(a){ub(g.vb,arguments)};
g.v=function(a,b){return a in g.vb?g.vb[a]:b};
g.yb=function(a,b){g.ma(a)&&(a=xb(a));return window.setTimeout(a,b)};
g.zb=function(a,b){g.ma(a)&&(a=xb(a));return window.setInterval(a,b)};
g.Ab=function(a){window.clearTimeout(a)};
g.Bb=function(a){window.clearInterval(a)};
xb=function(a){return a&&window.yterr?function(){try{return a.apply(this,arguments)}catch(b){throw g.Cb(b),b;}}:a};
g.Cb=function(a,b,c,d,e){var f=g.p("yt.logging.errors.log");f?f(a,b,c,d,e):(f=g.v("ERRORS",[]),f.push([a,b,c,d,e]),g.wb("ERRORS",f))};
naa=function(a,b,c,d,e){var f=!1;if(g.vb.No&&g.vb.No.log_window_onerror_fraction&&Math.random()<g.vb.No.log_window_onerror_fraction)f=!0;else for(var k=window.document.getElementsByTagName("script"),l=0,n=k.length;l<n;l++)if(0<k[l].src.indexOf("/debug-")){f=!0;break}f&&(e||(e=Error(),e.message=a,e.fileName=b,e.lineNumber=c,(0,window.isNaN)(d)||(e.columnNumber=d)),g.Cb(e))};
g.Eb=function(a){return a in g.Db};
g.Fb=function(a,b,c){var d=b||{};if(a=a in g.Db?g.Db[a]:c)for(var e in d)a=a.replace(new RegExp("\\$"+e,"gi"),function(){return d[e]});
return a};
ub=function(a,b){if(1<b.length){var c=b[0];a[c]=b[1]}else{var d=b[0];for(c in d)a[c]=d[c]}};
g.x=function(a,b,c){var d=Gb();if(d){var e=d.subscribe(a,function(){if(!Hb||Hb!=e){var d=arguments,k;k=function(){Ib[e]&&b.apply(c||window,d)};
try{Jb[a]?k():g.yb(k,0)}catch(l){g.Cb(l)}}},c);
Ib[e]=!0;Kb[a]||(Kb[a]=[]);Kb[a].push(e);return e}return 0};
g.Lb=function(a){var b=Gb();b&&("number"==typeof a?a=[a]:"string"==typeof a&&(a=[(0,window.parseInt)(a,10)]),(0,g.y)(a,function(a){b.unsubscribeByKey(a);delete Ib[a]}))};
g.z=function(a,b){var c=Gb();return c?c.publish.apply(c,arguments):!1};
g.Mb=function(a,b){Jb[a]=!0;var c=Gb(),c=c?c.publish.apply(c,arguments):!1;Jb[a]=!1;return c};
Gb=function(){return g.p("yt.pubsub.instance_")};
g.Nb=function(){return!!g.p("yt.scheduler.instance")};
g.Ob=function(a,b){(0,window.isNaN)(b)&&(b=void 0);var c=g.p("yt.scheduler.instance.addJob");return c?c(a,0,b):void 0===b?(a(),window.NaN):g.yb(a,b||0)};
g.Pb=function(a,b){return g.Ob(a,b)};
g.Rb=function(a){if(!(0,window.isNaN)(a)){var b=g.p("yt.scheduler.instance.cancelJob");b?b(a):g.Ab(a)}};
g.Sb=function(a){for(var b=0,c=a.length;b<c;b++)g.Rb(a[b])};
g.Tb=function(a,b,c,d,e){this.name=a;this.deps=b||[];this.page=c||"";this.G=d?xb(d):null;this.F=e?xb(e):null;this.D=[];this.A=this.C=0};
g.Vb=function(a){g.Rb(a.C);a.C=g.Pb((0,g.q)(a.init,a))};
g.Yb=function(a){a.name in Wb&&Xb(a.name);Wb[a.name]={reqs:[],disable:(0,g.q)(a.disable,a)};(0,g.y)(a.deps,function(b){if(!(b in Wb))throw Error("Module "+b+" required by "+a.name);Wb[b].reqs.push(a.name)});
a.enable()};
Xb=function(a){if(a in Wb){var b=Wb[a];(0,g.y)(b.reqs,function(a){Xb(a)});
try{b.disable()}catch(c){}delete Wb[a]}};
$b=function(){this.A="";this.C=Zb};
g.ac=function(a){return a instanceof $b&&a.constructor===$b&&a.C===Zb?a.A:"type_error:Const"};
g.bc=function(a){var b=new $b;b.A=a;return b};
dc=function(){this.A="";this.C=cc};
g.ec=function(a){if(a instanceof dc&&a.constructor===dc&&a.C===cc)return a.A;g.ga(a);return"type_error:SafeStyle"};
fc=function(a){var b=new dc;b.A=a;return b};
g.gc=function(a){var b="",c;for(c in a){if(!/^[-_a-zA-Z0-9]+$/.test(c))throw Error("Name allows only [-_a-zA-Z0-9], got: "+c);var d=a[c];if(null!=d){if(d instanceof $b)d=g.ac(d);else if(oaa.test(d)){for(var e=!0,f=!0,k=0;k<d.length;k++){var l=d.charAt(k);"'"==l&&f?e=!e:'"'==l&&e&&(f=!f)}e&&f||(d="zClosurez")}else d="zClosurez";b+=c+":"+d+";"}}return b?fc(b):paa};
g.ic=function(){this.A="";this.C=hc};
g.jc=function(a){if(a instanceof g.ic&&a.constructor===g.ic&&a.C===hc)return a.A;g.ga(a);return"type_error:SafeUrl"};
g.lc=function(a){if(a instanceof g.ic)return a;a=a.Nf?a.Pe():String(a);qaa.test(a)||(a="about:invalid#zClosurez");return g.kc(a)};
g.kc=function(a){var b=new g.ic;b.A=a;return b};
g.nc=function(){this.A="";this.C=mc};
g.oc=function(a){if(a instanceof g.nc&&a.constructor===g.nc&&a.C===mc)return a.A;g.ga(a);return"type_error:TrustedResourceUrl"};
g.qc=function(){this.A="";this.B=pc;this.C=null};
g.rc=function(a){if(a instanceof g.qc&&a.constructor===g.qc&&a.B===pc)return a.A;g.ga(a);return"type_error:SafeHtml"};
g.tc=function(a){if(a instanceof g.qc)return a;var b=null;a.xm&&(b=a.wg());a=g.xa(a.Nf?a.Pe():String(a));return g.sc(a,b)};
g.wc=function(a,b,c){if(!uc.test(a))throw Error("Invalid tag name <"+a+">.");if(a.toUpperCase()in raa)throw Error("Tag name <"+a+"> is not allowed for SafeHtml.");return g.vc(a,b,c)};
g.xc=function(a){function b(a){g.ha(a)?(0,g.y)(a,b):(a=g.tc(a),d+=g.rc(a),a=a.wg(),0==c?c=a:0!=a&&c!=a&&(c=null))}
var c=0,d="";(0,g.y)(arguments,b);return g.sc(d,c)};
g.sc=function(a,b){var c=new g.qc;c.A=a;c.C=b;return c};
g.vc=function(a,b,c){var d=null,e,f="";if(b)for(e in b){if(!uc.test(e))throw Error('Invalid attribute name "'+e+'".');var k=b[e];if(null!=k){var l,n=a;l=e;if(k instanceof $b)k=g.ac(k);else if("style"==l.toLowerCase()){if(!g.na(k))throw Error('The "style" attribute requires goog.html.SafeStyle or map of style properties, '+typeof k+" given: "+k);k instanceof dc||(k=g.gc(k));k=g.ec(k)}else{if(/^on/i.test(l))throw Error('Attribute "'+l+'" requires goog.string.Const value, "'+k+'" given.');if(l.toLowerCase()in
saa)if(k instanceof g.nc)k=g.oc(k);else if(k instanceof g.ic)k=g.jc(k);else if(g.ja(k))k=g.lc(k).Pe();else throw Error('Attribute "'+l+'" on tag "'+n+'" requires goog.html.SafeUrl, goog.string.Const, or string, value "'+k+'" given.');}k.Nf&&(k=k.Pe());l=l+'="'+g.xa(String(k))+'"';f+=" "+l}}e="<"+a+f;null!=c?g.ha(c)||(c=[c]):c=[];!0===taa[a.toLowerCase()]?e+=">":(d=g.xc(c),e+=">"+g.rc(d)+"</"+a+">",d=d.wg());(a=b&&b.dir)&&(/^(ltr|rtl|auto)$/i.test(a)?d=0:d=null);return g.sc(e,d)};
g.yc=function(a,b){a.innerHTML=g.rc(b)};
g.zc=function(a,b){var c;c=b instanceof g.ic?b:g.lc(b);a.href=g.jc(c)};
g.A=function(a,b){return a?a.dataset?a.dataset[g.Ac(b)]:a.getAttribute("data-"+b):null};
g.Bc=function(a,b){return a?a.dataset?g.Ac(b)in a.dataset:a.hasAttribute?!!a.hasAttribute("data-"+b):!!a.getAttribute("data-"+b):!1};
g.Ac=function(a){return Cc[a]||(Cc[a]=String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()}))};
g.Ec=function(a,b){var c=g.Dc(a);window.spf.script.load(a,c,b)};
g.Fc=function(a,b){var c=g.Dc(a);window.spf.script.ignore(c,b)};
g.Dc=function(a){var b="";if(a){var c=a.indexOf("jsbin/"),d=a.lastIndexOf(".js"),e=c+6;-1<c&&-1<d&&d>e&&(b=a.substring(e,d),b=b.replace(uaa,""),b=b.replace(vaa,""),b=b.replace("debug-",""),b=b.replace("tracing-",""))}return b};
g.Gc=function(a){return g.v("EXPERIMENT_FLAGS",{})[a]};
g.Hc=function(a,b){g.ac(a);g.ac(a);return g.sc(b,null)};
g.Ic=function(a){return eval("("+a+")")};
g.Jc=function(a,b,c,d,e,f,k){var l="";a&&(l+=a+":");c&&(l+="//",b&&(l+=b+"@"),l+=c,d&&(l+=":"+d));e&&(l+=e);f&&(l+="?"+f);k&&(l+="#"+k);return l};
g.Kc=function(a){return a?(0,window.decodeURI)(a):a};
g.Mc=function(a,b){return b.match(g.Lc)[a]||null};
g.Nc=function(a){return g.Kc(g.Mc(3,a))};
g.Oc=function(a){a=a.match(g.Lc);return g.Jc(null,null,null,null,a[5],a[6],a[7])};
g.Pc=function(a){var b=a.indexOf("#");return 0>b?a:a.substr(0,b)};
g.Qc=function(a){if(a[1]){var b=a[0],c=b.indexOf("#");0<=c&&(a.push(b.substr(c)),a[0]=b=b.substr(0,c));c=b.indexOf("?");0>c?a[1]="?":c==b.length-1&&(a[1]=void 0)}return a.join("")};
g.Rc=function(a,b,c){if(g.ha(b))for(var d=0;d<b.length;d++)g.Rc(a,String(b[d]),c);else null!=b&&c.push("&",a,""===b?"":"=",g.ua(b))};
Sc=function(a,b){for(var c in b)g.Rc(c,b[c],a);return a};
g.Tc=function(a){a=Sc([],a);a[0]="";return a.join("")};
g.Uc=function(a,b){return g.Qc(Sc([a],b))};
g.Vc=function(a){"?"==a.charAt(0)&&(a=a.substr(1));a=a.split("&");for(var b={},c=0,d=a.length;c<d;c++){var e=a[c].split("=");if(1==e.length&&e[0]||2==e.length){var f=g.va(e[0]||""),e=g.va(e[1]||"");f in b?g.ha(b[f])?g.Oa(b[f],e):b[f]=[b[f],e]:b[f]=e}}return b};
g.Wc=function(a,b){var c,d=b||{},e=a.split("#",2);c=e[0];var e=1<e.length?"#"+e[1]:"",f=c.split("?",2);c=f[0];var f=g.Vc(f[1]||""),k;for(k in d)f[k]=d[k];return g.Uc(c,f)+e};
waa=function(a){a=g.Xc(a);return g.Yc(a)||(null===a?!1:"google"==a[1]?!0:"google"==a[2]?"au"==a[0]&&"com"==a[1]?!0:"uk"==a[0]&&"co"==a[1]?!0:!1:!1)};
g.Yc=function(a){return null===a?!1:"com"==a[0]&&a[1].match(/^youtube(?:-nocookie)?$/)?!0:!1};
g.Xc=function(a){a=g.Nc(a);return null===a?null:a.split(".").reverse()};
g.Zc=function(a){return a&&"status"in a?a.status:-1};
g.$c=function(a){switch(g.Zc(a)){case 200:case 201:case 202:case 203:case 204:case 205:case 206:case 304:return!0;default:return!1}};
yaa=function(a,b,c,d,e,f,k){function l(){4==(n&&"readyState"in n?n.readyState:0)&&b&&xb(b)(n)}
var n=ad&&ad();if(!("open"in n))return null;"onloadend"in n?n.addEventListener("loadend",l,!1):n.onreadystatechange=l;c=(c||"GET").toUpperCase();d=d||"";n.open(c,a,!0);f&&(n.responseType=f);k&&(n.withCredentials=!0);f="POST"==c;if(e=xaa(a,e))for(var t in e)n.setRequestHeader(t,e[t]),"content-type"==t.toLowerCase()&&(f=!1);f&&n.setRequestHeader("Content-Type","application/x-www-form-urlencoded");n.send(d);return n};
xaa=function(a,b){b=b||{};var c;c||(c=window.location.href);var d=g.Mc(1,a),e=g.Nc(a);d&&e?(d=c,c=a.match(g.Lc),d=d.match(g.Lc),c=c[3]==d[3]&&c[1]==d[1]&&c[4]==d[4]):c=e?g.Nc(c)==e&&(Number(g.Mc(4,c))||null)==(Number(g.Mc(4,a))||null):!0;for(var f in bd){if((e=d=g.v(bd[f]))&&!(e=c)){var e=f,k=g.v("CORS_HEADER_WHITELIST")||{},l=g.Nc(a);e=l?(k=k[l])?g.Ka(k,e):!1:!0}e&&(b[f]=d)}return b};
g.cd=function(a,b){b.method="POST";b.ea||(b.ea={});return g.B(a,b)};
zaa=function(a,b){var c=g.v("XSRF_FIELD_NAME",void 0),d;b.headers&&(d=b.headers["Content-Type"]);return!b.My&&(!g.Nc(a)||b.withCredentials||g.Nc(a)==window.document.location.hostname)&&"POST"==b.method&&(!d||"application/x-www-form-urlencoded"==d)&&!(b.ea&&b.ea[c])};
g.B=function(a,b){var c=b.format||"JSON";b.xU&&(a=window.document.location.protocol+"//"+window.document.location.hostname+(window.document.location.port?":"+window.document.location.port:"")+a);var d=g.v("XSRF_FIELD_NAME",void 0),e=g.v("XSRF_TOKEN",void 0),f=b.ha;f&&(f[d]&&delete f[d],a=g.Wc(a,f));var k=b.postBody||"",f=b.ea;zaa(a,b)&&(f||(f={}),f[d]=e);f&&g.ja(k)&&(d=g.Vc(k),g.Za(d,f),k=b.Au&&"JSON"==b.Au?JSON.stringify(d):g.Tc(d));var l=!1,n,t=yaa(a,function(a){if(!l){l=!0;n&&g.Ab(n);var d=g.$c(a),
e=null;if(d||400<=a.status&&500>a.status)e=Aaa(c,a,b.qb);if(d)a:{switch(c){case "XML":d=0==(0,window.parseInt)(e&&e.return_code,10);break a;case "RAW":d=!0;break a}d=!!e}var e=e||{},f=b.context||g.da;d?b.X&&b.X.call(f,a,e):b.onError&&b.onError.call(f,a,e);b.Ya&&b.Ya.call(f,a,e)}},b.method,k,b.headers,b.responseType,b.withCredentials);
b.Bc&&0<b.timeout&&(n=g.yb(function(){l||(l=!0,t.abort(),g.Ab(n),b.Bc.call(b.context||g.da,t))},b.timeout));
return t};
Aaa=function(a,b,c){var d=null;switch(a){case "JSON":a=b.responseText;b=b.getResponseHeader("Content-Type")||"";a&&0<=b.indexOf("json")&&(d=g.Ic(a));break;case "XML":if(b=(b=b.responseXML)?g.dd(b):null)d={},(0,g.y)(b.getElementsByTagName("*"),function(a){d[a.tagName]=g.ed(a)})}c&&fd(d);
return d};
fd=function(a){if(g.na(a))for(var b in a)"html_content"==b||g.ta(b,"_html")?a[b]=g.Hc(g.bc("HTML that is escaped and sanitized server-side and passed through yt.net.ajax"),a[b]):fd(a[b])};
g.dd=function(a){return a?(a=("responseXML"in a?a.responseXML:a).getElementsByTagName("root"))&&0<a.length?a[0]:null:null};
g.ed=function(a){var b="";(0,g.y)(a.childNodes,function(a){b+=a.nodeValue});
return b};
g.gd=function(){return{apiaryHost:g.v("APIARY_HOST",void 0),jp:g.v("APIARY_HOST_FIRSTPARTY",void 0),gapiHintOverride:g.v("GAPI_HINT_OVERRIDE"),gapiHintParams:g.v("GAPI_HINT_PARAMS",void 0),innertubeApiKey:g.v("INNERTUBE_API_KEY",void 0),innertubeApiVersion:g.v("INNERTUBE_API_VERSION",void 0),AD:g.v("INNERTUBE_CONTEXT_CLIENT_NAME","WEB"),innertubeContextClientVersion:g.v("INNERTUBE_CONTEXT_CLIENT_VERSION",void 0),CD:g.v("INNERTUBE_CONTEXT_HL",void 0),BD:g.v("INNERTUBE_CONTEXT_GL",void 0),rO:g.v("XHR_APIARY_HOST",
void 0)}};
g.hd=function(a){a={client:{hl:a.CD,gl:a.BD,clientName:a.AD,clientVersion:a.innertubeContextClientVersion}};g.v("DELEGATED_SESSION_ID")&&(a.user={onBehalfOfUser:g.v("DELEGATED_SESSION_ID")});return a};
id=function(){this.A=g.gd()};
g.jd=function(a,b,c){this.A=a;this.B=b;this.C=c};
g.od=function(a,b){g.kd[a.endpoint]=g.kd[a.endpoint]||[];var c=g.kd[a.endpoint];c.push(a.Cb);ld[a.endpoint]=b;20<=c.length?g.md():g.nd()};
g.md=function(){g.Ab(g.pd);if(!g.Ua(g.kd)){for(var a in g.kd){var b=g.qd[a];if(!b){b=ld[a];if(!b)continue;b=new b;g.qd[a]=b}var c=b.C();c.requestTimeMs=Math.round(rd());c[Baa[a]]=g.kd[a];b.B(a,c,{});delete g.kd[a]}g.Ua(g.kd)||g.nd()}};
g.nd=function(){g.Ab(g.pd);g.pd=g.yb(g.md,g.v("VISIBILITY_TIMEOUT",1E4))};
sd=function(a,b,c){var d={};d.eventTimeMs=Math.round(c||rd());d[a]=b;g.od({endpoint:"log_event",Cb:d},id)};
g.td=function(){var a=g.v("client-screen-nonce",void 0);a||(a=g.v("EVENT_ID",void 0));return a};
g.ud=function(a,b){this.x=g.ca(a)?a:0;this.y=g.ca(b)?b:0};
g.vd=function(a,b){this.width=a;this.height=b};
g.wd=function(){return g.ab("iPhone")&&!g.ab("iPod")&&!g.ab("iPad")};
xd=function(){var a=g.da.document;return a?a.documentMode:void 0};
g.Ad=function(a){return yd[a]||(yd[a]=0<=g.Ca(g.zd,a))};
g.Cd=function(a){return Number(g.Bd)>=a};
g.C=function(a){return g.ja(a)?window.document.getElementById(a):a};
g.Dd=function(a){return g.ja(a)?window.document.getElementById(a):a};
g.D=function(a,b){var c=b||window.document,d=null;c.getElementsByClassName?d=c.getElementsByClassName(a)[0]:c.querySelectorAll&&c.querySelector?d=c.querySelector("."+a):d=g.Ed(window.document,"*",a,b)[0];return d||null};
g.Ed=function(a,b,c,d){a=d||a;b=b&&"*"!=b?b.toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(b||c))return a.querySelectorAll(b+(c?"."+c:""));if(c&&a.getElementsByClassName){a=a.getElementsByClassName(c);if(b){d={};for(var e=0,f=0,k;k=a[f];f++)b==k.nodeName&&(d[e++]=k);d.length=e;return d}return a}a=a.getElementsByTagName(b||"*");if(c){d={};for(f=e=0;k=a[f];f++)b=k.className,"function"==typeof b.split&&g.Ka(b.split(/\s+/),c)&&(d[e++]=k);d.length=e;return d}return a};
g.Gd=function(a,b){g.Ra(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:Fd.hasOwnProperty(d)?a.setAttribute(Fd[d],b):g.sa(d,"aria-")||g.sa(d,"data-")?a.setAttribute(d,b):a[d]=b})};
g.Id=function(a){return g.Hd(a||window)};
g.Hd=function(a){a=a.document;a=g.Jd(a)?a.documentElement:a.body;return new g.vd(a.clientWidth,a.clientHeight)};
g.Ld=function(a){var b=g.Kd(a);a=a.parentWindow||a.defaultView;return g.E&&g.Ad("10")&&a.pageYOffset!=b.scrollTop?new g.ud(b.scrollLeft,b.scrollTop):new g.ud(a.pageXOffset||b.scrollLeft,a.pageYOffset||b.scrollTop)};
g.Kd=function(a){return a.scrollingElement?a.scrollingElement:!g.Md&&g.Jd(a)?a.documentElement:a.body||a.documentElement};
g.Od=function(a,b,c){return g.Nd(window.document,arguments)};
g.Nd=function(a,b){var c=b[0],d=b[1];if(!Caa&&d&&(d.name||d.type)){c=["<",c];d.name&&c.push(' name="',g.xa(d.name),'"');if(d.type){c.push(' type="',g.xa(d.type),'"');var e={};g.Za(e,d);delete e.type;d=e}c.push(">");c=c.join("")}c=a.createElement(c);d&&(g.ja(d)?c.className=d:g.ha(d)?c.className=d.join(" "):g.Gd(c,d));2<b.length&&g.Pd(a,c,b,2);return c};
g.Pd=function(a,b,c,d){function e(c){c&&b.appendChild(g.ja(c)?a.createTextNode(c):c)}
for(;d<c.length;d++){var f=c[d];!g.ia(f)||g.na(f)&&0<f.nodeType?e(f):(0,g.y)(Daa(f)?g.Na(f):f,e)}};
g.Jd=function(a){return"CSS1Compat"==a.compatMode};
g.Qd=function(a){for(var b;b=a.firstChild;)a.removeChild(b)};
g.Rd=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b)};
g.Sd=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b.nextSibling)};
Eaa=function(a){if(!a)return null;if(a.firstChild)return a.firstChild;for(;a&&!a.nextSibling;)a=a.parentNode;return a?a.nextSibling:null};
Faa=function(a){if(!a)return null;if(!a.previousSibling)return a.parentNode;for(a=a.previousSibling;a&&a.lastChild;)a=a.lastChild;return a};
g.Td=function(a){return 9==a.nodeType?a:a.ownerDocument||a.document};
Daa=function(a){if(a&&"number"==typeof a.length){if(g.na(a))return"function"==typeof a.item||"string"==typeof a.item;if(g.ma(a))return"function"==typeof a.item}return!1};
g.Ud=function(a,b,c,d){c||(a=a.parentNode);for(c=0;a&&(null==d||c<=d);){if(b(a))return a;a=a.parentNode;c++}return null};
g.Vd=function(a,b,c){a&&(c&&(c=g.$a,c=!(c&&0<=c.toLowerCase().indexOf("cobalt"))),c?a&&(a=g.Od("iframe",{src:'javascript:"data:text/html,<body><img src=\\"'+a+'\\"></body>"',style:"display:none"}),g.Td(a).body.appendChild(a)):Gaa(a,b))};
g.Wd=function(a){try{window.navigator&&window.navigator.sendBeacon&&window.navigator.sendBeacon(a,"")||g.Vd(a,void 0)}catch(b){g.Vd(a,void 0)}};
Gaa=function(a,b){var c=new window.Image,d=""+Haa++;Xd[d]=c;c.onload=c.onerror=function(){b&&Xd[d]&&b();delete Xd[d]};
c.src=a};
g.Yd=function(a,b){this.version=a;this.args=b};
g.Zd=function(a,b){this.topic=a;this.vf=b};
g.ae=function(a,b){var c=g.$d();return c?c.publish.call(c,a.toString(),a,b):!1};
g.$d=function(){return g.p("yt.pubsub2.instance_")};
be=function(a){g.Yd.call(this,1,arguments)};
de=function(a){var b=a||window;if(!(b.performance&&b.performance.timing&&b.performance.getEntriesByType))return{Fk:0,Wv:0};a=g.Id(b);for(var c=[],d=b.document.getElementsByTagName("*"),e=0,f=d.length;e<f;e++){var k=d[e];if("IMG"==k.tagName||"IFRAME"==k.tagName){var l=ce(k,k.src,a);if(l){if("IFRAME"==k.tagName){var n;try{n=de(k.contentWindow).Fk}catch(t){n=0}0<n&&(l.timing=n)}c.push(l)}}(l=b.getComputedStyle(k)["background-image"])&&(l=Iaa.exec(l))&&1<l.length&&(l=ce(k,l[1],a))&&c.push(l)}n=b.performance.getEntriesByType("resource");
k=b.performance.getEntriesByType("mark");d={};e=0;for(f=n.length;e<f;e++)l=n[e],d[l.name]=l.responseEnd;e=0;for(f=k.length;e<f;e++)l=k[e],"mark_iframe_loaded: "==l.name.slice(0,20)&&(d[l.name.slice(20)]=l.startTime);e=0;for(f=c.length;e<f;e++)k=c[e],k.timing||(k.timing=d[k.url]||0);b=Jaa(b,n);a=Kaa(b,a,c);k=c=0;if(a.length)for(d=n=0,e=a.length;d<e;d++)f=a[d],k=f.timing-k,0<k&&1>n&&(c+=(1-n)*k),k=f.timing,n=f.progress;return{Fk:Math.round(c||b),Wv:k}};
ce=function(a,b,c){if(b&&a.getBoundingClientRect){var d=a.getBoundingClientRect();a=Math.max(d.top,0);var e=Math.min(d.right,c.width);c=Math.min(d.bottom,c.height);d=Math.max(d.left,0);if(c>a&&e>d)return new Laa(a,e,c,d,b)}return null};
Jaa=function(a,b){var c,d=a.performance.timing.navigationStart;if("msFirstPaint"in a.performance.timing)c=a.performance.timing.A-d;else if("chrome"in a&&"loadTimes"in a.chrome){var e=a.chrome.loadTimes(),f=e.firstPaintTime;if(0<f){var k=e.startLoadTime;"requestTime"in e&&(k=e.requestTime);f>=k&&(c=1E3*(f-k))}}if(void 0===c||0>c||12E4<c){c=a.performance.timing.responseStart-d;for(var l={},d=a.document.getElementsByTagName("head")[0].children,e=0,f=d.length;e<f;e++)k=d[e],"SCRIPT"==k.tagName&&k.src&&
!k.async?l[k.src]=!0:"LINK"==k.tagName&&"stylesheet"==k.rel&&k.href&&(l[k.href]=!0);b.some(function(a){if(!l[a.name]||"script"!=a.initiatorType&&"link"!=a.initiatorType)return!0;a=a.responseEnd;if(void 0===c||a>c)c=a})}return Math.max(c,0)||0};
Kaa=function(a,b,c){for(var d={0:0},e=0,f=0,k=c.length;f<k;f++){var l=c[f],n=a;l.timing>a&&(n=l.timing);d[n]||(d[n]=0);l=(l.A-l.D)*(l.B-l.C);d[n]+=l;e+=l}f=b.width*b.height;0<f&&(f=.1*Math.max(f-e,0),a in d||(d[a]=0),d[a]+=f,e+=f);a=[];if(e){for(var t in d)b=new Maa((0,window.parseFloat)(t),d[t]),a.push(b);a.sort(function(a,b){return a.timing-b.timing});
f=d=0;for(k=a.length;f<k;f++)b=a[f],d+=b.xl,b.progress=d/e}return a};
Laa=function(a,b,c,d,e){this.A=c;this.C=d;this.B=b;this.D=a;this.url=e};
Maa=function(a,b){this.xl=b;this.timing=a};
Naa=function(){if("cold"==ee().yt_lt){var a=fe(),b=ge(),c;for(c in a)c in b||he(c,a[c])}};
g.ke=function(a,b,c){b||ie(a);fe(c)[a]=b||rd();he(a,b,c)||je(!1,c)};
he=function(a,b,c){ge(c)[a]=b;if(g.Gc("csi_on_gel")){var d=le(c).nonce;if(!d){var e;a:{if(window.crypto&&window.crypto.getRandomValues)try{var f=Array(16),k=new window.Uint8Array(16);window.crypto.getRandomValues(k);for(d=0;d<f.length;d++)f[d]=k[d];e=f;break a}catch(l){}e=Array(16);for(f=0;16>f;f++){k=(0,g.F)();for(d=0;d<k%23;d++)e[f]=Math.random();e[f]=Math.floor(256*Math.random())}if(me)for(f=1,k=0;k<me.length;k++)e[f%16]=e[f%16]^e[(f-1)%16]/4^me.charCodeAt(k),f++}f=[];for(k=0;k<e.length;k++)f.push("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_".charAt(e[k]&
63));d=f.join("");le(c).nonce=d}c=d;"_start"==a?sd("latencyActionBaselined",{clientActionNonce:c},b):sd("latencyActionTicked",{tickName:a,clientActionNonce:c},b);return!0}return!1};
ne=function(a,b){ee(void 0).yt_sts=a;g.ke("_start",b,void 0)};
pe=function(a){oe(a);Oaa();g.m("yt.timing.pingSent_",!1,void 0)};
Paa=function(){var a=g.td();a&&(ee(void 0).csn=a)};
qe=function(a){a=fe(a);if(a.aft)return a.aft;for(var b=g.v("TIMING_AFT_KEYS",["ol"]),c=b.length,d=0;d<c;d++){var e=a[b[d]];if(e)return e}return window.NaN};
re=function(a,b){var c=b||le(void 0).span,d;d=a.redirectEnd-a.redirectStart;0<d&&(c.rtime_=d);d=a.domainLookupEnd-a.domainLookupStart;0<d&&(c.dns_=d);d=a.connectEnd-a.connectStart;0<d&&(c.tcp_=d);d=a.connectEnd-a.secureConnectionStart;a.secureConnectionStart>=a.navigationStart&&0<d&&(c.stcp_=d);d=a.responseStart-a.requestStart;0<d&&(c.req_=d);d=a.responseEnd-a.responseStart;0<d&&(c.rcv_=d)};
te=function(a){return Math.round(se.timing.navigationStart+a)};
Qaa=function(a){var b=window.location.protocol,c=se.getEntriesByType("resource"),d=c.filter(function(a){return 0==a.name.indexOf(b+"//fonts.googleapis.com/css?family=")})[0],c=c.filter(function(a){return 0==a.name.indexOf(b+"//fonts.gstatic.com/s/")}).reduce(function(a,b){return b.duration>a.duration?b:a},{duration:0});
d&&0<d.startTime&&0<d.responseEnd&&(a.wfcs=te(d.startTime),a.wfce=te(d.responseEnd));c&&0<c.startTime&&0<c.responseEnd&&(a.wffs=te(c.startTime),a.wffe=te(c.responseEnd))};
xe=function(a){var b=fe(a),c=le(a).span,d=ee(a),e=g.p("yt.timing.reportbuilder_");if(e){if(e=e(b,c,d,a))ue(e),pe(a)}else{var f=g.v("TIMING_ACTION",void 0),k=g.v("CSI_SERVICE_NAME","youtube"),e={v:2,s:k,action:f},l;se.now&&se.timing?(l=se.timing.navigationStart+se.now(),l=Math.round((0,g.F)()-l)):l=null;null!=l&&(d.yt_hrd=l);l=g.v("TIMING_INFO",{});for(var n in l)d[n]=l[n];n=d.srt;delete d.srt;var t;void 0===b.srt&&(n||0===n||(t=se.timing||{},n=Math.max(0,t.responseStart-t.navigationStart),(0,window.isNaN)(n)&&
d.pt&&(n=d.pt)),n||0===n)&&(d.srt=Math.round(n));d.h5jse&&(l=window.location.protocol+g.p("ytplayer.config.assets.js"),(l=se.getEntriesByName?se.getEntriesByName(l)[0]:null)?d.h5jse=Math.round(d.h5jse-l.responseEnd):delete d.h5jse);b.aft=qe(a);l=b._start;if("cold"==d.yt_lt){t||(t=se.timing||{});var w;a:if(w=t,w.msFirstPaint)w=Math.max(0,w.msFirstPaint);else{var H=window.chrome;if(H&&(H=H.loadTimes,g.ma(H))){var H=H(),R=1E3*Math.min(H.requestTime||window.Infinity,H.startLoadTime||window.Infinity),
R=window.Infinity===R?0:w.navigationStart-R;w=Math.max(0,Math.round(1E3*H.firstPaintTime+R)||0);break a}w=0}0<w&&w>l&&(b.fpt=w);re(t,c);se.getEntriesByType&&Qaa(b);(t=g.v("SPEEDINDEX_FOR_ACTIONS",void 0))&&-1<t.indexOf(f)&&(f=rd(),t=de(),w=rd(),0<t.Fk&&(d.si=t.Fk,b.vsc=te(t.Wv),b.sics=f,b.sice=w));f=[];if(window.document.querySelector&&se&&se.getEntriesByName)for(var Z in ve)if(t=window.document.querySelector(Z))w="",H=t.nodeName,"SCRIPT"==H?w=t.src:"LINK"==H&&(w=t.href),w&&(t=se.getEntriesByName(w))&&
t[0]&&f.push(ve[Z]+"."+Math.round(t[0].duration));f.length&&(d.rs=f.join(","))}t=fe(a);Z=t.pbr;f=t.vc;t=t.pbs;Z&&f&&t&&Z<f&&f<t&&1==ee(a).yt_vis&&"youtube"==k&&(ee(a).yt_lt="hot_bg",k=b.vc,Z=b.pbs,delete b.aft,d.aft=Math.round(Z-k));(k=g.v("PREVIOUS_ACTION"))&&(d.pa=k);d.p=g.v("CLIENT_PROTOCOL")||"unknown";d.t=g.v("CLIENT_TRANSPORT")||"unknown";window.navigator&&window.navigator.sendBeacon&&(d.ba=1);for(var la in d)"_"!=la.charAt(0)&&(e[la]=d[la]);b.ps=rd();d={};la=[];for(var wa in b)"_"!=wa.charAt(0)&&
(w=Math.round(b[wa]-l),g.Gc("enable_negative_ticks")||(w=Math.max(w,0)),d[wa]=w,la.push(wa+"."+w));e.rt=la.join(",");b=e;wa=[];for(var Ga in c)"_"!=Ga.charAt(0)&&wa.push(Ga+"."+Math.round(c[Ga]));b.it=wa.join(",");(Ga=g.p("ytdebug.logTiming"))&&Ga(e,d,c);pe(a);g.v("EXP_DEFER_CSI_PING")?(we(),g.m("yt.timing.deferredPingArgs_",e,void 0),a=g.yb(we,0),g.m("yt.timing.deferredPingTimer_",a,void 0)):ue(e);g.ae(Raa,new be(d.aft+(n||0)))}};
je=function(a,b){var c=g.v("TIMING_ACTION",void 0),d=fe(b);if(g.p("yt.timing.ready_")&&c&&d._start&&qe(b)){var c=!0,e=g.v("TIMING_WAIT",[]);if(!a&&e.length)for(var f=0,k=e.length;f<k;++f)if(!(e[f]in d)){c=!1;break}(c||b)&&xe(b)}};
ue=function(a){if(g.v("DEBUG_CSI_DATA")){var b=g.p("yt.timing.csiData");b||(b=[],g.m("yt.timing.csiData",b,void 0));b.push({page:window.location.href,time:new Date,args:a})}g.v("EXP_DEFER_CSI_PING")&&(g.Ab(g.p("yt.timing.deferredPingTimer_")),g.m("yt.timing.deferredPingArgs_",null,void 0));var b="",c;for(c in a)b+="&"+c+"="+a[c];a="/csi_204?"+b.substring(1);window.navigator&&window.navigator.sendBeacon?g.Wd(a):g.Vd(a);g.m("yt.timing.pingSent_",!0,void 0)};
we=function(a){if(g.v("EXP_DEFER_CSI_PING")){var b=g.p("yt.timing.deferredPingArgs_");b&&(a&&(b.yt_fss=a),ue(b))}};
fe=function(a){return le(a).tick};
ee=function(a){return le(a).info};
ge=function(a){a=le(a);"gel"in a||(a.gel={});return a.gel};
le=function(a){return g.p("ytcsi."+(a||"")+"data_")||oe(a)};
oe=function(a){var b={tick:{},span:{},info:{}};g.m("ytcsi."+(a||"")+"data_",b,void 0);return b};
ye=function(a){if(!g.p("yt.timing.pingSent_")){if(!g.Gc("send_empty_timing")){var b=g.v("CSI_SERVICE_NAME","youtube");if(!g.v("TIMING_ACTION",void 0)||!b)return}g.ke("aa");ee(void 0).ap=1;ee(void 0).yt_fss=a;xe()}};
g.ze=function(a,b){g.Vd("/gen_204?"+a,b)};
g.Ae=function(a){if(a.classList)return a.classList;a=a.className;return g.ja(a)&&a.match(/\S+/g)||[]};
g.G=function(a,b){return a.classList?a.classList.contains(b):g.Ka(g.Ae(a),b)};
g.I=function(a,b){a.classList?a.classList.add(b):g.G(a,b)||(a.className+=0<a.className.length?" "+b:b)};
g.J=function(a,b){a.classList?a.classList.remove(b):g.G(a,b)&&(a.className=(0,g.Be)(g.Ae(a),function(a){return a!=b}).join(" "))};
g.Ce=function(a,b,c){c?g.I(a,b):g.J(a,b)};
g.De=function(a){var b=a.cloneNode(!1);"TR"==b.tagName||"SELECT"==b.tagName?(0,g.y)(a.childNodes,function(a){b.appendChild(g.De(a))}):b.innerHTML=a.innerHTML;
return b};
g.Ee=function(a){this.type="";this.state=this.source=this.data=this.currentTarget=this.relatedTarget=this.target=null;this.charCode=this.keyCode=0;this.shiftKey=this.ctrlKey=this.altKey=!1;this.rotation=this.clientY=this.clientX=0;this.scale=1;this.changedTouches=this.touches=null;if(a=a||window.event){this.event=a;for(var b in a)b in Saa||(this[b]=a[b]);this.scale=a.scale;this.rotation=a.rotation;(b=a.target||a.srcElement)&&3==b.nodeType&&(b=b.parentNode);this.target=b;if(b=a.relatedTarget)try{b=
b.nodeName?b:null}catch(c){b=null}else"mouseover"==this.type?b=a.fromElement:"mouseout"==this.type&&(b=a.toElement);this.relatedTarget=b;this.clientX=void 0!=a.clientX?a.clientX:a.pageX;this.clientY=void 0!=a.clientY?a.clientY:a.pageY;this.keyCode=a.keyCode?a.keyCode:a.which;this.charCode=a.charCode||("keypress"==this.type?this.keyCode:0);this.altKey=a.altKey;this.ctrlKey=a.ctrlKey;this.shiftKey=a.shiftKey;this.mn=a.pageX;this.nn=a.pageY}};
g.Ge=function(a,b,c,d){a.addEventListener&&("mouseenter"!=b||"onmouseenter"in window.document?"mouseleave"!=b||"onmouseenter"in window.document?"mousewheel"==b&&"MozBoxSizing"in window.document.documentElement.style&&(b="MozMousePixelScroll"):b="mouseout":b="mouseover");return g.Ta(g.Fe,function(e){return e[0]==a&&e[1]==b&&e[2]==c&&e[4]==!!d})};
g.K=function(a,b,c,d){if(!a||!a.addEventListener&&!a.attachEvent)return"";d=!!d;var e=g.Ge(a,b,c,d);if(e)return e;var e=++He.count+"",f=!("mouseenter"!=b&&"mouseleave"!=b||!a.addEventListener||"onmouseenter"in window.document),k;k=f?function(d){d=new g.Ee(d);if(!g.Ud(d.relatedTarget,function(b){return b==a},!0))return d.currentTarget=a,d.type=b,c.call(a,d)}:function(b){b=new g.Ee(b);
b.currentTarget=a;return c.call(a,b)};
k=xb(k);a.addEventListener?("mouseenter"==b&&f?b="mouseover":"mouseleave"==b&&f?b="mouseout":"mousewheel"==b&&"MozBoxSizing"in window.document.documentElement.style&&(b="MozMousePixelScroll"),a.addEventListener(b,k,d)):a.attachEvent("on"+b,k);g.Fe[e]=[a,b,c,k,d];return e};
g.Ie=function(a){a&&("string"==typeof a&&(a=[a]),(0,g.y)(a,function(a){if(a in g.Fe){var c=g.Fe[a],d=c[0],e=c[1],f=c[3],c=c[4];d.removeEventListener?d.removeEventListener(e,f,c):d.detachEvent&&d.detachEvent("on"+e,f);delete g.Fe[a]}}))};
g.Je=function(a){a=a||window.event;a.returnValue=!1;a.preventDefault&&a.preventDefault()};
g.Le=function(){if(null==g.p("_lact",window)){var a=(0,window.parseInt)(g.v("LACT"),10),a=(0,window.isFinite)(a)?(0,g.F)()-Math.max(a,0):-1;g.m("_lact",a,window);-1==a&&Ke();g.K(window.document,"keydown",Ke);g.K(window.document,"keyup",Ke);g.K(window.document,"mousedown",Ke);g.K(window.document,"mouseup",Ke);g.x("page-mouse",Ke);g.x("page-scroll",Ke);g.x("page-resize",Ke)}};
Ke=function(){null==g.p("_lact",window)&&(g.Le(),g.p("_lact",window));var a=(0,g.F)();g.m("_lact",a,window);g.z("USER_ACTIVE")};
g.Me=function(){var a=g.p("_lact",window);return null==a?-1:Math.max((0,g.F)()-a,0)};
Ne=function(a){a=a||{};this.url=a.url||"";this.urlV9As2=a.url_v9as2||"";this.args=a.args||g.Xa(Taa);this.assets=a.assets||{};this.attrs=a.attrs||g.Xa(Uaa);this.params=a.params||g.Xa(Vaa);this.minVersion=a.min_version||"8.0.0";this.fallback=a.fallback||null;this.fallbackMessage=a.fallbackMessage||null;this.html5=!!a.html5;this.disable=a.disable||{};this.loaded=!!a.loaded;this.messages=a.messages||{}};
g.Oe=function(a){a instanceof Ne||(a=new Ne(a));return a};
Qe=function(){return null!=g.Pe};
g.Re=function(){return g.Pe?g.Pe.invoke():null};
Se=function(){return(0,window.parseInt)(g.v("DCLKSTAT",0),10)};
g.Te=function(a){this.A=a||{cookie:""}};
g.Ve=function(a){a=(a.A.cookie||"").split(g.Ue);for(var b=[],c=[],d,e,f=0;e=a[f];f++)d=e.indexOf("="),-1==d?(b.push(""),c.push(e)):(b.push(e.substring(0,d)),c.push(e.substring(d+1)));return{keys:b,values:c}};
g.Xe=function(a,b,c,d){g.We.set(""+a,b,c,"/",d||"youtube.com")};
g.$e=function(a,b,c){var d=g.v("VALID_SESSION_TEMPDATA_DOMAINS",[]),e=g.Nc(window.location.href);e&&d.push(e);e=g.Nc(a);if(g.Ka(d,e)||!e&&g.sa(a,"/"))if(a=g.Oc(a),a=g.Pc(a))c?(c=(0,window.parseInt)(c,10),(0,window.isFinite)(c)&&0<c&&(Ye(a,b,c),Ze(b))):(Ye(a,b),Ze(b))};
Ye=function(a,b,c){var d=g.v("ST_BASE36",!0),e;e=g.v("ST_SHORT",!0)?"ST-":"s_tempdata-";a=e=d?e+g.Da(a).toString(36):e+g.Da(a);c=c||5;b=b?g.Tc(b):"";g.Xe(a,b,c)};
Ze=function(a){if(a){a=a.itct||a.ved;var b=g.p("yt.logging.screenreporter.storeParentElement");a&&b&&b(new g.jd(a))}};
g.af=function(a,b,c){c=c||"";g.zc(window.location,g.Uc(a,b||{})+c)};
g.bf=function(a,b){b&&g.$e(a,b);(window.ytspf||{}).enabled?window.spf.navigate(a):g.af(a)};
g.cf=function(a,b,c){var d=g.v("EVENT_ID");d&&(b||(b={}),b.ei||(b.ei=d));b&&g.$e(a,b);if(c)return!1;g.bf(a);return!0};
g.ff=function(){return g.Md?"Webkit":g.df?"Moz":g.E?"ms":g.ef?"O":null};
g.gf=function(){return g.Md?"-webkit":g.df?"-moz":g.E?"-ms":g.ef?"-o":null};
g.hf=function(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d};
g.jf=function(a,b){return a&&b?b instanceof g.hf?b.left>=a.left&&b.right<=a.right&&b.top>=a.top&&b.bottom<=a.bottom:b.x>=a.left&&b.x<=a.right&&b.y>=a.top&&b.y<=a.bottom:!1};
g.kf=function(a,b,c,d){this.left=a;this.top=b;this.width=c;this.height=d};
g.mf=function(a,b){var c=lf[b];if(!c){var d=Ea(b),c=d;void 0===a.style[d]&&(d=g.ff()+g.Fa(d),void 0!==a.style[d]&&(c=d));lf[b]=c}return c};
g.nf=function(a,b){var c=a.style[Ea(b)];return"undefined"!==typeof c?c:a.style[g.mf(a,b)]||""};
g.of=function(a,b){"number"==typeof a&&(a=(b?Math.round(a):a)+"px");return a};
g.pf=function(a,b){a.style.height=g.of(b,!0)};
g.qf=function(a,b){a.style.width=g.of(b,!0)};
g.rf=function(a,b){a.style.display=b?"":"none"};
g.tf=function(){var a=g.We.get("PREF",void 0);if(a)for(var a=(0,window.unescape)(a).split("&"),b=0;b<a.length;b++){var c=a[b].split("="),d=c[0];(c=c[1])&&(g.sf[d]=c.toString())}};
uf=function(a){if(/^f([1-9][0-9]*)$/.test(a))throw"ExpectedRegexMatch: "+a;};
vf=function(a){if(!/^\w+$/.test(a))throw"ExpectedRegexMismatch: "+a;};
g.wf=function(a){a=void 0!==g.sf[a]?g.sf[a].toString():null;return null!=a&&/^[A-Fa-f0-9]+$/.test(a)?(0,window.parseInt)(a,16):null};
g.xf=function(a,b){return!!((g.wf("f"+(Math.floor(b/31)+1))||0)&1<<b%31)};
g.yf=function(a,b){(a=g.C(a))&&a.style&&(g.rf(a,b),g.Ce(a,"hid",!b))};
g.zf=function(a){return(a=g.C(a))?!("none"==a.style.display||g.G(a,"hid")):!1};
Waa=function(a){if(a=g.C(a))g.zf(a)?(g.rf(a,!1),g.I(a,"hid")):(g.rf(a,!0),g.J(a,"hid"))};
g.L=function(a){(0,g.y)(arguments,function(a){!g.ia(a)||a instanceof window.Element?g.yf(a,!0):(0,g.y)(a,function(a){g.L(a)})})};
g.M=function(a){(0,g.y)(arguments,function(a){!g.ia(a)||a instanceof window.Element?g.yf(a,!1):(0,g.y)(a,function(a){g.M(a)})})};
g.Af=function(a){(0,g.y)(arguments,function(a){g.ia(a)?(0,g.y)(a,function(a){g.Af(a)}):Waa(a)})};
g.Cf=function(){this.A=this.minor=this.major=0;this.C="";var a=g.p("window.navigator.plugins"),b=g.p("window.navigator.mimeTypes"),a=a&&a["Shockwave Flash"],b=b&&b["application/x-shockwave-flash"],b=a&&b&&b.enabledPlugin&&a.description||"";if(a=b){var c=a.indexOf("Shockwave Flash");0<=c&&(a=a.substr(c+15));for(var c=a.split(" "),d="",a="",e=0,f=c.length;e<f;e++)if(d)if(a)break;else a=c[e];else d=c[e];d=d.split(".");c=(0,window.parseInt)(d[0],10)||0;d=(0,window.parseInt)(d[1],10)||0;e=0;if("r"==a.charAt(0)||
"d"==a.charAt(0))e=(0,window.parseInt)(a.substr(1),10)||0;a=[c,d,e]}else a=[0,0,0];this.C=b;b=a;this.major=b[0];this.minor=b[1];this.A=b[2];if(0>=this.major){var k,l,n,t;if(g.Bf)try{k=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(w){k=null}else n=window.document.body,t=window.document.createElement("object"),t.setAttribute("type","application/x-shockwave-flash"),k=n.appendChild(t);if(k&&"GetVariable"in k)try{l=k.GetVariable("$version")}catch(w){l=""}n&&t&&n.removeChild(t);(k=l||
"")?(k=k.split(" ")[1].split(","),k=[(0,window.parseInt)(k[0],10)||0,(0,window.parseInt)(k[1],10)||0,(0,window.parseInt)(k[2],10)||0]):k=[0,0,0];this.major=k[0];this.minor=k[1];this.A=k[2]}};
Df=function(a,b,c,d){b="string"==typeof b?b.split("."):[b,c,d];b[0]=(0,window.parseInt)(b[0],10)||0;b[1]=(0,window.parseInt)(b[1],10)||0;b[2]=(0,window.parseInt)(b[2],10)||0;return a.major>b[0]||a.major==b[0]&&a.minor>b[1]||a.major==b[0]&&a.minor==b[1]&&a.A>=b[2]};
Ef=function(a){return-1<a.C.indexOf("Gnash")&&-1==a.C.indexOf("AVM2")||9==a.major&&1==a.minor||9==a.major&&0==a.minor&&1==a.A?!1:9<=a.major};
Xaa=function(a){return g.Ff?!Df(a,11,2):g.Gf?!Df(a,11,3):!Ef(a)};
Hf=function(a,b,c){if(b){a=g.ja(a)?g.Dd(a):a;var d=g.Xa(c.attrs);d.tabindex=0;var e=g.Xa(c.params);e.flashvars=g.Tc(c.args);if(g.Bf){d.classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000";e.movie=b;b=window.document.createElement("object");for(var f in d)b.setAttribute(f,d[f]);for(f in e)d=window.document.createElement("param"),d.setAttribute("name",f),d.setAttribute("value",e[f]),b.appendChild(d)}else{d.type="application/x-shockwave-flash";d.src=b;b=window.document.createElement("embed");b.setAttribute("name",
d.id);for(f in d)b.setAttribute(f,d[f]);for(f in e)b.setAttribute(f,e[f])}e=window.document.createElement("div");e.appendChild(b);a.innerHTML=e.innerHTML}};
g.Kf=function(a,b){a=g.ja(a)?g.Dd(a):a;b=g.Oe(b);if(window!=window.top){var c=null;window.document.referrer&&(c=window.document.referrer.substring(0,128));b.args.framer=c}c=g.Cf.getInstance();Df(c,b.minVersion)?(c=If(b,c),Hf(a,c,b)):Jf(a,b,c)};
Lf=function(a,b,c){if(a&&a.attrs&&a.attrs.id){a=g.Oe(a);var d=!!b,e=g.C(a.attrs.id),f=e?e.parentNode:null;if(e&&f){if(window!=window.top){var k=null;if(window.document.referrer){var l=window.document.referrer.substring(0,128);waa(l)||(k=l)}else k="unknown";k&&(d=!0,a.args.framer=k)}k=g.Cf.getInstance();if(Df(k,a.minVersion)){var l=If(a,k),n="";-1<window.navigator.userAgent.indexOf("Sony/COM2")||(n=e.getAttribute("src")||e.movie);(n!=l||d)&&Hf(f,l,a);Xaa(k)&&Yaa()}else Jf(f,a,k);c&&c()}else g.yb(function(){Lf(a,
b,c)},50)}};
Jf=function(a,b,c){0==c.major&&b.fallback?b.fallback():0==c.major&&b.fallbackMessage?b.fallbackMessage():a.innerHTML='<div id="flash-upgrade">'+g.Fb("FLASH_UPGRADE",void 0,'You need to upgrade your Adobe Flash Player to watchthis video. <br> <a href="http://get.adobe.com/flashplayer/">Download it from Adobe.</a>')+"</div>"};
If=function(a,b){var c;(c=Ef(b)&&a.url)||(c=(-1<window.navigator.userAgent.indexOf("Sony/COM2")&&!Df(b,9,1,58)?!1:!0)&&a.urlV9As2);return c||a.url};
Yaa=function(){var a=g.C("flash10-promo-div"),b=g.xf(g.tf.getInstance(),107);a&&!b&&g.L(a)};
g.Mf=function(a,b){var c=a.match(Zaa);window.spf.style.load(a,c?c[1]:"",b)};
g.Nf=function(a){g.pb.call(this);this.A=[];this.C=a||this};
Of=function(a,b,c,d){d=xb((0,g.q)(d,a.C));b.addEventListener(c,d);a.A.push({target:b,name:c,Vb:d})};
Pf=function(a){for(;a.A.length;){var b=a.A.pop();b.target.removeEventListener(b.name,b.Vb)}};
Sf=function(a,b){g.pb.call(this);this.O=this.D=a;this.ia=b;this.L=!1;this.api={};this.Qa=this.T=null;this.Y=new g.tb;g.sb(this,this.Y);this.B={};this.F=this.Xa=this.C=this.lb=this.A=null;this.aa=!1;this.W=this.G=this.M=this.R=null;this.Za={};this.gc=["onReady"];this.ga=new g.Nf(this);g.sb(this,this.ga);this.sb=null;this.Hb=window.NaN;this.la={};Qf(this);this.ge("onDetailedError",(0,g.q)(this.xI,this));this.ge("onTabOrderChange",(0,g.q)(this.ey,this));this.ge("onTabAnnounce",(0,g.q)(this.Yo,this));
this.ge("WATCH_LATER_VIDEO_ADDED",(0,g.q)(this.AI,this));this.ge("WATCH_LATER_VIDEO_REMOVED",(0,g.q)(this.BI,this));g.Rf||(this.ge("onMouseWheelCapture",(0,g.q)(this.hI,this)),this.ge("onMouseWheelRelease",(0,g.q)(this.iI,this)));this.ge("onAdAnnounce",(0,g.q)(this.Yo,this));this.H=new g.Nf(this);g.sb(this,this.H);this.hb=!1;this.bb=null};
Uf=function(a,b){a.lb=b;a.A=b.clone();a.C=a.A.attrs.id||a.C;"video-player"==a.C&&(a.C=a.ia,a.A.attrs.id=a.ia);a.O.id==a.C&&(a.C+="-player",a.A.attrs.id=a.C);a.A.args.enablejsapi="1";a.A.args.playerapiid=a.ia;a.Xa||(a.Xa=Tf(a,a.A.args.jsapicallback||"onYouTubePlayerReady"));a.A.args.jsapicallback=null;var c=a.A.attrs.width;c&&g.qf(a.O,Number(c)||c);(c=a.A.attrs.height)&&g.pf(a.O,Number(c)||c)};
Vf=function(a){a.A.loaded||(a.A.loaded=!0,"0"!=a.A.args.autoplay?a.api.loadVideoByPlayerVars(a.A.args):a.api.cueVideoByPlayerVars(a.A.args))};
Wf=function(a){if(!g.ca(a.A.disable.flash)){var b=a.A.disable,c;c=Df(g.Cf.getInstance(),a.A.minVersion);b.flash=!c}return!a.A.disable.flash};
Zf=function(a,b){if((!b||(5!=($aa[b.errorCode]||5)?0:-1!=aba.indexOf(b.errorCode)))&&Wf(a)){var c=Xf(a);c&&c.stopVideo&&c.stopVideo();var d=a.A;c&&c.getUpdatedConfigurationData&&(c=c.getUpdatedConfigurationData(),d=g.Oe(c));d.args.autoplay=1;d.args.html5_unavailable="1";Uf(a,d);Yf(a,"flash")}};
Yf=function(a,b){if(!a.isDisposed()){if(!b){var c;if(!(c=!a.A.html5&&Wf(a))){if(!g.ca(a.A.disable.html5)){var d;c=!0;void 0!=a.A.args.deviceHasDisplay&&(c=a.A.args.deviceHasDisplay);if(2.2==$f)d=!0;else{a:{var e=c;c=g.p("yt.player.utils.videoElement_");c||(c=window.document.createElement("video"),g.m("yt.player.utils.videoElement_",c,void 0));try{if(c.canPlayType)for(var e=e?bba:cba,f=0;f<e.length;f++)if(c.canPlayType(e[f])){d=null;break a}d="fmt.noneavailable"}catch(k){d="html5.missingapi"}}d=!d}d&&
(d=ag(a)||a.A.assets.js);a.A.disable.html5=!d;d||(a.A.args.html5_unavailable="1")}c=!!a.A.disable.html5}b=c?Wf(a)?"flash":"unsupported":"html5"}("flash"==b?a.oO:"html5"==b?a.pO:a.qO).call(a)}};
ag=function(a){var b=!0,c=Xf(a);c&&a.A&&(a=a.A,b=g.A(c,"version")==a.assets.js);return b&&!!g.p("yt.player.Application.create")};
Xf=function(a){var b=g.C(a.C);!b&&a.O&&a.O.querySelector&&(b=a.O.querySelector("#"+a.C));return b};
bg=function(a,b,c){var d=b[c];return function(){try{return a.sb=null,d.apply(b,arguments)}catch(e){"Bad NPObject as private data!"!=e.message&&"sendAbandonmentPing"!=c&&(e.message+=" ("+c+")",a.sb=e,g.Cb(e,"WARNING"))}}};
Qf=function(a){a.L=!1;if(a.Qa)for(var b in a.B)a.Qa(b,a.B[b]);for(var c in a.la)g.Ab((0,window.parseInt)(c,10));a.la={};a.T=null;a.Qa=null;for(var d in a.api)a.api[d]=null;a.api.addEventListener=(0,g.q)(a.ge,a);a.api.removeEventListener=(0,g.q)(a.vM,a);a.api.destroy=(0,g.q)(a.dispose,a);a.api.getLastError=(0,g.q)(a.Dz,a);a.api.getPlayerType=(0,g.q)(a.Sz,a);a.api.getCurrentVideoConfig=(0,g.q)(a.az,a);a.api.loadNewVideoConfig=(0,g.q)(a.xo,a);a.api.isReady=(0,g.q)(a.EO,a)};
Tf=function(a,b){var c=b;if("string"==typeof b){if(a.Za[b])return a.Za[b];c=function(){var a=g.p(b);a&&a.apply(g.da,arguments)};
a.Za[b]=c}return c?c:null};
dba=function(a,b){var c="ytPlayer"+b+a.ia;a.B[b]=c;g.da[c]=function(c){var e=g.yb(function(){a.isDisposed()||(a.Y.qa(b,c),g.Va(a.la,String(e)))},0);
g.Wa(a.la,String(e),!0)};
return c};
cg=function(a){return(a=Xf(a))?"div"==a.tagName.toLowerCase()?"html5":"flash":null};
dg=function(a){g.ke("dcp");a.cancel();Qf(a);a.F=null;a.A&&(a.A.loaded=!1);var b=Xf(a);"html5"==cg(a)?a.M=b:b&&b.destroy&&b.destroy();g.Qd(a.D);Pf(a.ga);a.G=null;a.W=null};
g.gg=function(a,b){a=g.ja(a)?g.Dd(a):a;b=g.Oe(b);var c=g.eg+"_"+g.pa(a),d=g.fg[c];if(d)return d.xo(b),d.api;d=new Sf(a,c);g.fg[c]=d;g.z("player-added",d.api);g.qb(d,g.r(eba,d));g.yb(function(){d.xo(b)},0);
return d.api};
eba=function(a){g.fg[a.getId()]=null};
g.hg=function(a){a=g.C(a);if(!a)return null;var b=g.eg+"_"+g.pa(a),c=g.fg[b];c||(c=new Sf(a,b),g.fg[b]=c);return c.api};
g.ig=function(){return g.G(g.C("page-container"),"remote-connected")};
fba=function(){g.m("yt.abuse.botguardInitialized",Qe,void 0);g.m("yt.abuse.invokeBotguard",g.Re,void 0);g.m("yt.abuse.dclkstatus.checkDclkStatus",Se,void 0);g.m("yt.player.exports.navigate",g.cf,void 0);g.m("yt.player.embed",g.gg,void 0);g.m("yt.player.getPlayerByElement",g.hg,void 0);g.m("yt.util.activity.init",g.Le,void 0);g.m("yt.util.activity.getTimeSinceActive",g.Me,void 0);g.m("yt.util.activity.setTimestamp",Ke,void 0);var a=g.p("ytplayer.config");jg(a);g.p("ytspf.enabled")&&(kg=g.zb(lg,5E3),
(a=g.mg())?(a.addEventListener("onReady",lg),a.addEventListener("onStateChange",lg)):ng("unable to init PP monitor"))};
jg=function(a){for(var b in g.fg){var c=g.fg[b];c&&c.cancel()}if(a=a||null){b=g.mg();var d=!0,c=g.og;g.og=null;b&&b.getVideoData&&c&&(d=b.getVideoData(),d=!!c.fullscreen||d.video_id!=a.args.video_id||d.list!=a.args.list||d.video_id!=c.videoId||d.list!=c.listId);d?(pg="",g.gg("player-api",a)):b.playVideo();a=g.Oe(a);a.loaded=!0}lg();g.m("ytplayer.config",a,void 0)};
g.mg=function(){var a=g.p("yt.player.getPlayerByElement");return a?a("player-api"):null};
lg=function(){var a=g.mg();if(a){var b;b=g.C("player");b=!b||g.G(b,"off-screen");var c=1==(a&&a.isReady()?a.getPlayerState():void 0),d="watch"==g.v("PAGE_NAME"),e=g.ig();!c||d||e||(ng("PP playing off watch (paused)"),a.pauseVideo());b&&d?ng("PP off-screen on watch"):b||d||ng("PP !off-screen off watch")}};
ng=function(a){var b=g.v("PAGE_NAME");b&&(b=[b,pg,g.p("_spf_state.nav-counter")],a+="("+b.join(",")+")",g.m("yt.www.persistentplayer.issue",a,void 0),g.Cb(Error(a),"WARNING"))};
g.qg=function(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0};
g.rg=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};
g.tg=function(a,b){this.A=0;this.L=void 0;this.D=this.C=this.B=null;this.F=this.G=!1;if(a!=g.ea)try{var c=this;a.call(b,function(a){g.sg(c,2,a)},function(a){g.sg(c,3,a)})}catch(d){g.sg(this,3,d)}};
ug=function(){this.next=this.context=this.C=this.D=this.A=null;this.B=!1};
g.wg=function(a,b,c){var d=vg.get();d.D=a;d.C=b;d.context=c;return d};
gba=function(a,b,c){xg(a,b,c,null)||mb(g.r(b,a))};
g.yg=function(a){return new g.tg(function(b,c){var d=a.length,e=[];if(d)for(var f=function(a,c){d--;e[a]=c;0==d&&b(e)},k=function(a){c(a)},l=0,n;l<a.length;l++)n=a[l],gba(n,g.r(f,l),k);
else b(e)})};
zg=function(a,b){if(0==a.A)if(a.B){var c=a.B;if(c.C){for(var d=0,e=null,f=null,k=c.C;k&&(k.B||(d++,k.A==a&&(e=k),!(e&&1<d)));k=k.next)e||(f=k);e&&(0==c.A&&1==d?zg(c,b):(f?(d=f,d.next==c.D&&(c.D=d),d.next=d.next.next):Ag(c),Bg(c,e,3,b)))}a.B=null}else g.sg(a,3,b)};
g.Dg=function(a,b){a.C||2!=a.A&&3!=a.A||Cg(a);a.D?a.D.next=b:a.C=b;a.D=b};
g.Fg=function(a,b,c,d){var e=g.wg(null,null,null);e.A=new g.tg(function(a,k){e.D=b?function(c){try{var e=b.call(d,c);a(e)}catch(t){k(t)}}:a;
e.C=c?function(b){try{var e=c.call(d,b);!g.ca(e)&&b instanceof Eg?k(b):a(e)}catch(t){k(t)}}:k});
e.A.B=a;g.Dg(a,e);return e.A};
g.sg=function(a,b,c){0==a.A&&(a==c&&(b=3,c=new TypeError("Promise cannot resolve to itself")),a.A=1,xg(c,a.W,a.H,a)||(a.L=c,a.A=b,a.B=null,Cg(a),3!=b||c instanceof Eg||hba(a,c)))};
xg=function(a,b,c,d){if(a instanceof g.tg)return g.Dg(a,g.wg(b||g.ea,c||null,d)),!0;if(g.rg(a))return a.then(b,c,d),!0;if(g.na(a))try{var e=a.then;if(g.ma(e))return iba(a,e,b,c,d),!0}catch(f){return c.call(d,f),!0}return!1};
iba=function(a,b,c,d,e){function f(a){l||(l=!0,d.call(e,a))}
function k(a){l||(l=!0,c.call(e,a))}
var l=!1;try{b.call(a,k,f)}catch(n){f(n)}};
Cg=function(a){a.G||(a.G=!0,mb(a.O,a))};
Ag=function(a){var b=null;a.C&&(b=a.C,a.C=b.next,b.next=null);a.C||(a.D=null);return b};
Bg=function(a,b,c,d){if(3==c&&b.C&&!b.B)for(;a&&a.F;a=a.B)a.F=!1;if(b.A)b.A.B=null,Gg(b,c,d);else try{b.B?b.D.call(b.context):Gg(b,c,d)}catch(e){Hg.call(null,e)}fb(vg,b)};
Gg=function(a,b,c){2==b?a.D.call(a.context,c):a.C&&a.C.call(a.context,c)};
hba=function(a,b){a.F=!0;mb(function(){a.F&&Hg.call(null,b)})};
Eg=function(a){g.ra.call(this,a)};
lba=function(){var a=g.Id(),a=new g.kf(0,0,a.width,a.height);g.ke("vpc");for(var b=window.document.querySelector(".yt-lockup-thumbnail img[data-ytimg]"),c=b.length,d=[],e=!0,f=0;f<c;f++){var k=b[f],l=k.getBoundingClientRect(),l=new g.kf(l.top,l.left,l.width,l.height);a.left<=l.left+l.width&&l.left<=a.left+a.width&&a.top<=l.top+l.height&&l.top<=a.top+a.height&&(d.push(jba(k)),k.loadTime||(e=!1))}e&&(ee(void 0).yt_eil=1);return g.yg(d).then(kba)};
kba=function(a){return Math.max(Math.max.apply(null,a),0)};
jba=function(a){return new g.tg(function(b){if(a.loadTime)b((0,window.parseInt)(a.loadTime,10));else{var c=g.K(a,"load",function(){if(a.loadTime){var d=(0,window.parseInt)(a.loadTime,10);g.Ie(c);b(d)}});
Ig.push(c)}})};
Kg=function(){g.ke("ol");g.v("CSI_TICK_PAINT_TIME")?window.requestAnimationFrame&&!window.document.hidden?window.requestAnimationFrame(function(){(0,window.setTimeout)(function(){g.ke("cpt");Jg()},0)}):window.document.hidden?(g.ke("cpt"),Jg()):(0,window.setTimeout)(function(){g.ke("cpt");
Jg()},0):Jg();
g.v("CSI_VIEWPORT")&&lba().then(function(a){g.ke("vpl",a)})};
Jg=function(){Lg("init");var a=g.v("PAGE_NAME",void 0);a&&Lg("init-"+a)};
Lg=function(a){g.Nb()?Mg.push(g.Ob(g.r(g.Mb,a),0)):g.z(a)};
Ng=function(){g.Sb(Mg);Mg.length=0;g.Ie(Ig);Ig.length=0;var a=g.v("PAGE_NAME",void 0);a&&g.Mb("dispose-"+a);g.Mb("dispose")};
mba=function(){Kg()};
nba=function(){g.v("TIMING_REPORT_ON_UNLOAD")&&je(!0);ye("u");we("u");Ng();g.Mb("pageunload")};
Og=function(){Ke()};
Pg=function(){window.yt_spf_loaded_history=!0;g.v("EXP_LACT_HISTORY")&&Ke()};
Ug=function(){Qg=1;Rg=Sg=0;g.v("TIMING_REPORT_ON_UNLOAD")&&je(!0);ye("n");we("n");pe();ne("n");ie("mark_navigation_requested");Tg(oba);g.Mb("navigate")};
Yg=function(a){a=a.detail.part||a.detail.partial;g.ke("nc"+Sg);++Sg;if(!a.data||!a.data.deferDispose){var b=1==Qg;Qg=2;b?(Tg(pba),Vg()):Tg(qba);if(b=a.data&&a.data.swfcfg)Wg(a.timing,b.args),Xg(b)}};
Zg=function(){g.ke("np"+Rg);++Rg};
$g=function(a){a=a.detail.response;var b=1==Qg;Qg=3;b&&(Tg(rba),Vg());if(b=a.data&&a.data.swfcfg)Wg(a.timing,b.args),Xg(b)};
ch=function(a){g.ke("nd");a=a.detail.response;g.ah=a.cacheKey;a=a.timing;var b=window._spf_state,b=b&&b["nav-counter"]||0;ee(void 0).yt_nav=b;ne("ne",a.responseStart);b=Math.max(0,a.responseStart-a.navigationStart);ee(void 0).srt=b;b=a.spfCached?"hot":"warm";ee(void 0).yt_lt=b;b=+!!a.spfPrefetched;ee(void 0).yt_pft=b;g.ke("pfs",a.fetchStart);g.ke("pfrs",a.responseStart);"redirectStart"in a&&re(a);Tg(bh);window.document.getElementById("content").style.height="";Kg();Qg=0};
dh=function(a){var b=a.detail.url;if(a=a.detail.err)a.message&&(a.message+=" (url: "+b+")"),g.Cb(a)};
eh=function(a){g.ze(g.Tc({spfreload:"1",url:a.detail.url,reason:a.detail.reason}))};
tba=function(){sba();g.wb("SERVED_VIA_SPF_HISTORY",!!window.yt_spf_loaded_history);window.yt_spf_loaded_history=!1};
uba=function(){};
Vg=function(){var a=window.document.getElementById("content");-1<a.className.indexOf("spf-animate")&&(a.style.height=a.clientHeight+"px");Ng();var a=g.v("TIMING_ACTION"),b;for(b in g.vb)delete g.vb[b];g.wb("PREVIOUS_ACTION",a);g.m("ytplayer.config",null,void 0);if((b=g.mg())&&b.stopVideo){if(b.stopVideo(),b=b.getLastError())pg=b,(b=g.C("movie_player"))&&b.stopVideo?(b.stopVideo(),pg="recovered"):pg="missing2"}else pg="missing";lg()};
Xg=function(a){"cfg"in fe(void 0)||g.ke("cfg");jg(a)};
Tg=function(a){var b=window.document.getElementById("progress");b||(b=window.document.createElement("div"),b.id="progress",b.appendChild(window.document.createElement("dt")),b.appendChild(window.document.createElement("dd")),window.document.body.appendChild(b));g.Rb(fh);fh=g.Pb(function(){var c=a[0],d=a[1],e=a[2];b.className="";var f=b.style;f.transitionDuration=f.webkitTransitionDuration=c+"ms";f.width=d+"%";g.Ab(gh);gh=g.yb(function(){b.className=e},c)},0)};
sba=function(){var a=bh[0]+50;g.Ab(gh);gh=g.yb(function(){var a=window.document.getElementById("progress");a&&a.parentNode.removeChild(a)},a)};
Wg=function(a,b){var c=a&&a.spfCached,d=a&&a.spfPrefetched,e=[];c&&!d&&(0,g.y)(vba,function(a){a in b&&(delete b[a],e.push(a))});
g.v("EXP_DEBUG_PREFETCH")&&(e.sort(),c={a:"removeNonCacheableVideoVars",cached:c,prefetched:d,deleted:e.join("")},g.ze(g.Tc(c)))};
hh=function(){g.Tb.call(this,"www/base");this.B=0};
ih=function(a){(a=a.detail.name)&&Xb(a)};
g.aa=[];g.jh=g.jh||{};g.da=this;oa="closure_uid_"+(1E9*Math.random()>>>0);aaa=0;g.F=Date.now||function(){return+new Date};g.qa[" "]=g.ea;g.u(g.ra,Error);g.ra.prototype.name="CustomError";var eaa,faa,gaa,haa,iaa,jaa,daa;g.Aa=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};
eaa=/&/g;faa=/</g;gaa=/>/g;haa=/"/g;iaa=/'/g;jaa=/\x00/g;daa=/[\x00&<>"']/;g.kh=String.prototype.repeat?function(a,b){return a.repeat(b)}:function(a,b){return Array(b+1).join(a)};
g.wba=2147483648*Math.random()|0;g.Ja=Array.prototype.indexOf?function(a,b,c){return Array.prototype.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;
if(g.ja(a))return g.ja(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};
g.xba=Array.prototype.lastIndexOf?function(a,b,c){return Array.prototype.lastIndexOf.call(a,b,null==c?a.length-1:c)}:function(a,b,c){c=null==c?a.length-1:c;
0>c&&(c=Math.max(0,a.length+c));if(g.ja(a))return g.ja(b)&&1==b.length?a.lastIndexOf(b,c):-1;for(;0<=c;c--)if(c in a&&a[c]===b)return c;return-1};
g.y=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=g.ja(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};
g.Be=Array.prototype.filter?function(a,b,c){return Array.prototype.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,k=g.ja(a)?a.split(""):a,l=0;l<d;l++)if(l in k){var n=k[l];
b.call(c,n,l,a)&&(e[f++]=n)}return e};
g.lh=Array.prototype.map?function(a,b,c){return Array.prototype.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=g.ja(a)?a.split(""):a,k=0;k<d;k++)k in f&&(e[k]=b.call(c,f[k],k,a));
return e};
g.mh=Array.prototype.reduce?function(a,b,c,d){d&&(b=(0,g.q)(b,d));return Array.prototype.reduce.call(a,b,c)}:function(a,b,c,d){var e=c;
(0,g.y)(a,function(c,k){e=b.call(d,e,c,k,a)});
return e};
g.nh=Array.prototype.some?function(a,b,c){return Array.prototype.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=g.ja(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;
return!1};
g.oh=Array.prototype.every?function(a,b,c){return Array.prototype.every.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=g.ja(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&!b.call(c,e[f],f,a))return!1;
return!0};g.ph=g.Pa(!1);g.qh=g.Pa(!0);g.rh=g.Pa(null);var Ya="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");a:{var sh=g.da.navigator;if(sh){var th=sh.userAgent;if(th){g.$a=th;break a}}g.$a=""};var ob;eb.prototype.get=function(){var a;0<this.C?(this.C--,a=this.A,this.A=a.next,a.next=null):a=this.B();return a};var lb=new eb(function(){return new hb},function(a){a.reset()},100);
gb.prototype.remove=function(){var a=null;this.A&&(a=this.A,this.A=this.A.next,this.A||(this.C=null),a.next=null);return a};
hb.prototype.set=function(a,b){this.oe=a;this.scope=b;this.next=null};
hb.prototype.reset=function(){this.next=this.scope=this.oe=null};var ib,jb=!1,kb=new gb;g.pb.prototype.Md=!1;g.pb.prototype.isDisposed=function(){return this.Md};
g.pb.prototype.dispose=function(){this.Md||(this.Md=!0,this.S())};
g.pb.prototype.S=function(){if(this.Kb)for(;this.Kb.length;)this.Kb.shift()()};g.u(g.tb,g.pb);g.h=g.tb.prototype;g.h.subscribe=function(a,b,c){var d=this.sd[a];d||(d=this.sd[a]=[]);var e=this.D;this.A[e]=a;this.A[e+1]=b;this.A[e+2]=c;this.D=e+3;d.push(e);return e};
g.h.unsubscribe=function(a,b,c){if(a=this.sd[a]){var d=this.A;if(a=g.Ia(a,function(a){return d[a+1]==b&&d[a+2]==c}))return this.td(a)}return!1};
g.h.td=function(a){var b=this.A[a];if(b){var c=this.sd[b];0!=this.B?(this.C.push(a),this.A[a+1]=g.ea):(c&&g.Ma(c,a),delete this.A[a],delete this.A[a+1],delete this.A[a+2])}return!!b};
g.h.qa=function(a,b){var c=this.sd[a];if(c){for(var d=Array(arguments.length-1),e=1,f=arguments.length;e<f;e++)d[e-1]=arguments[e];if(this.F)for(e=0;e<c.length;e++){var k=c[e];maa(this.A[k+1],this.A[k+2],d)}else{this.B++;try{for(e=0,f=c.length;e<f;e++)k=c[e],this.A[k+1].apply(this.A[k+2],d)}finally{if(this.B--,0<this.C.length&&0==this.B)for(;c=this.C.pop();)this.td(c)}}return 0!=e}return!1};
g.h.clear=function(a){if(a){var b=this.sd[a];b&&((0,g.y)(b,this.td,this),delete this.sd[a])}else this.A.length=0,this.sd={}};
g.h.pb=g.ba(1);g.h.S=function(){g.tb.K.S.call(this);this.clear();this.C.length=0};var rd;g.vb=window.yt&&window.yt.config_||window.ytcfg&&window.ytcfg.data_||{};g.m("yt.config_",g.vb,void 0);g.m("yt.tokens_",window.yt&&window.yt.tokens_||{},void 0);g.Db=window.yt&&window.yt.msgs_||g.p("window.ytcfg.msgs")||{};g.m("yt.msgs_",g.Db,void 0);rd=window.performance&&window.performance.timing&&window.performance.now&&window.__yt_experimental_now?function(){return window.performance.timing.navigationStart+window.performance.now()}:function(){return(new Date).getTime()};
g.Bf="Microsoft Internet Explorer"==window.navigator.appName;var yba=g.p("yt.pubsub.instance_")||new g.tb;g.tb.prototype.subscribe=g.tb.prototype.subscribe;g.tb.prototype.unsubscribeByKey=g.tb.prototype.td;g.tb.prototype.publish=g.tb.prototype.qa;g.tb.prototype.clear=g.tb.prototype.clear;g.m("yt.pubsub.instance_",yba,void 0);var Ib=g.p("yt.pubsub.subscribedKeys_")||{};g.m("yt.pubsub.subscribedKeys_",Ib,void 0);var Kb=g.p("yt.pubsub.topicToKeys_")||{};g.m("yt.pubsub.topicToKeys_",Kb,void 0);var Jb=g.p("yt.pubsub.isSynchronous_")||{};
g.m("yt.pubsub.isSynchronous_",Jb,void 0);var Hb=g.p("yt.pubsub.skipSubId_")||null;g.m("yt.pubsub.skipSubId_",Hb,void 0);g.h=g.Tb.prototype;g.h.IM=function(){this.Pj()||this.init()};
g.h.enable=function(){this.A=1;(0,g.y)("string"==typeof this.page?[this.page]:this.page,function(a){a&&(this.subscribe("init-"+a,this.IM,this),this.subscribe("dispose-"+a,this.dispose,this),g.v("PAGE_NAME")==a&&g.Vb(this))},this)};
g.h.init=function(){g.Rb(this.C);this.A=2;this.G&&this.G()};
g.h.Pj=function(){return 2==this.A};
g.h.dispose=function(){this.A=3;g.Rb(this.C);this.F&&this.F()};
g.h.disable=function(){this.A=4;this.clear();try{this.dispose()}catch(a){g.Cb(a)}};
g.h.subscribe=function(a,b,c){a=g.x(a,b,c);this.D.push(a);return a};
g.h.clear=function(){g.Lb(this.D);this.D=[]};var Wb=g.p("yt.modules.registry_")||{};g.m("yt.modules.registry_",Wb,void 0);var taa={area:!0,base:!0,br:!0,col:!0,command:!0,embed:!0,hr:!0,img:!0,input:!0,keygen:!0,link:!0,meta:!0,param:!0,source:!0,track:!0,wbr:!0};g.zba=RegExp("[A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]");g.Aba=RegExp("^[^\u0591-\u06ef\u06fa-\u07ff\u200f\ufb1d-\ufdff\ufe70-\ufefc]*[A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]");g.uh=RegExp("^[^A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]*[\u0591-\u06ef\u06fa-\u07ff\u200f\ufb1d-\ufdff\ufe70-\ufefc]");$b.prototype.Nf=!0;$b.prototype.Pe=function(){return this.A};
$b.prototype.toString=function(){return"Const{"+this.A+"}"};
var Zb={};dc.prototype.Nf=!0;var cc={};dc.prototype.Pe=function(){return this.A};
var paa=fc(""),oaa=/^([-,."'%_!# a-zA-Z0-9]+|(?:rgb|hsl)a?\([0-9.%, ]+\))$/;g.ic.prototype.Nf=!0;g.ic.prototype.Pe=function(){return this.A};
g.ic.prototype.xm=!0;g.ic.prototype.wg=function(){return 1};
var qaa=/^(?:(?:https?|mailto|ftp):|[^&:/?#]*(?:[/?#]|$))/i,hc={};g.kc("about:blank");g.nc.prototype.Nf=!0;g.nc.prototype.Pe=function(){return this.A};
g.nc.prototype.xm=!0;g.nc.prototype.wg=function(){return 1};
var mc={};var uc,saa,raa,pc;g.qc.prototype.xm=!0;g.qc.prototype.wg=function(){return this.C};
g.qc.prototype.Nf=!0;g.qc.prototype.Pe=function(){return this.A};
uc=/^[a-zA-Z0-9-]+$/;saa={action:!0,cite:!0,data:!0,formaction:!0,href:!0,manifest:!0,poster:!0,src:!0};raa={APPLET:!0,BASE:!0,EMBED:!0,IFRAME:!0,LINK:!0,MATH:!0,META:!0,OBJECT:!0,SCRIPT:!0,STYLE:!0,SVG:!0,TEMPLATE:!0};pc={};g.Bba=g.sc("<!DOCTYPE html>",0);g.vh=g.sc("",0);g.wh=g.sc("<br>",0);var Cc={};var uaa=/\.vflset|-vfl[a-zA-Z0-9_+=-]+/,vaa=/-[a-zA-Z]{2,3}_[a-zA-Z]{2,3}(?=(\/|$))/;g.Cba=Math.sign||function(a){return 0<a?1:0>a?-1:a};g.xh="StopIteration"in g.da?g.da.StopIteration:{message:"StopIteration",stack:""};g.Dba=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;g.Lc=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/;var ad=null;"undefined"!=typeof window.XMLHttpRequest?ad=function(){return new window.XMLHttpRequest}:"undefined"!=typeof window.ActiveXObject&&(ad=function(){return new window.ActiveXObject("Microsoft.XMLHTTP")});var bd={"X-YouTube-Client-Name":"INNERTUBE_CONTEXT_CLIENT_NAME","X-YouTube-Client-Version":"INNERTUBE_CONTEXT_CLIENT_VERSION","X-Youtube-Identity-Token":"XSRF_TOKEN","X-YouTube-Page-CL":"PAGE_CL","X-YouTube-Page-Label":"PAGE_BUILD_LABEL","X-YouTube-Variants-Checksum":"VARIANTS_CHECKSUM"};id.prototype.C=function(){return{context:g.hd(this.A)}};
id.prototype.B=function(a,b,c){g.cd("//"+this.A.rO+("/youtubei/"+this.A.innertubeApiVersion+"/"+a)+"?alt=json&key="+this.A.innertubeApiKey,{headers:{"Content-Type":"application/json","X-Goog-Visitor-Id":g.v("VISITOR_DATA")},ea:b,Au:"JSON",Bc:c.Bc,X:c.X,onError:c.onError,timeout:c.timeout})};var Baa,ld;Baa={log_event:"events",log_interaction:"interactions"};g.qd={};ld={};g.pd=0;g.kd=g.p("yt.logging.transport.logsQueue_")||{};g.m("yt.logging.transport.logsQueue_",g.kd,void 0);g.h=g.ud.prototype;g.h.clone=function(){return new g.ud(this.x,this.y)};
g.h.ceil=function(){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y);return this};
g.h.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};
g.h.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};
g.h.scale=function(a,b){var c=g.ka(b)?b:a;this.x*=a;this.y*=c;return this};g.h=g.vd.prototype;g.h.clone=function(){return new g.vd(this.width,this.height)};
g.h.xl=function(){return this.width*this.height};
g.h.aspectRatio=function(){return this.width/this.height};
g.h.isEmpty=function(){return!this.xl()};
g.h.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};
g.h.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};
g.h.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};
g.h.scale=function(a,b){var c=g.ka(b)?b:a;this.width*=a;this.height*=c;return this};var Ah,Bh,yd,Fh;g.ef=g.ab("Opera");g.E=g.bb();g.yh=g.ab("Edge");g.zh=g.yh||g.E;g.df=g.ab("Gecko")&&!(g.ya(g.$a.toLowerCase(),"webkit")&&!g.ab("Edge"))&&!(g.ab("Trident")||g.ab("MSIE"))&&!g.ab("Edge");g.Md=g.ya(g.$a.toLowerCase(),"webkit")&&!g.ab("Edge");g.Md&&g.ab("Mobile");g.Gf=g.ab("Macintosh");g.Ff=g.ab("Windows");g.Eba=g.ab("Linux")||g.ab("CrOS");Ah=g.da.navigator||null;Ah&&g.ya(Ah.appVersion||"","X11");g.Fba=g.ab("Android");g.Gba=g.wd();g.Hba=g.ab("iPad");g.Iba=g.ab("iPod");
a:{var Ch="",Dh=function(){var a=g.$a;if(g.df)return/rv\:([^\);]+)(\)|;)/.exec(a);if(g.yh)return/Edge\/([\d\.]+)/.exec(a);if(g.E)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(g.Md)return/WebKit\/(\S+)/.exec(a);if(g.ef)return/(?:Version)[ \/]?(\S+)/.exec(a)}();
Dh&&(Ch=Dh?Dh[1]:"");if(g.E){var Eh=xd();if(null!=Eh&&Eh>(0,window.parseFloat)(Ch)){Bh=String(Eh);break a}}Bh=Ch}g.zd=Bh;yd={};Fh=g.da.document;g.Bd=Fh&&g.E?xd()||("CSS1Compat"==Fh.compatMode?(0,window.parseInt)(g.zd,10):5):void 0;var Caa;Caa=!g.E||g.Cd(9);g.Jba=!g.df&&!g.E||g.E&&g.Cd(9)||g.df&&g.Ad("1.9.1");g.Gh=g.E&&!g.Ad("9");g.Kba=g.E||g.ef||g.Md;g.Lba=g.E&&!g.Cd(9);var Fd={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};g.Rf=g.ab("Firefox");g.Hh=g.wd()||g.ab("iPod");g.Ih=g.ab("iPad");g.Mba=g.ab("Android")&&!(g.cb()||g.ab("Firefox")||g.ab("Opera")||g.ab("Silk"));g.Jh=g.cb();g.Kh=g.ab("Safari")&&!(g.cb()||g.ab("Coast")||g.ab("Opera")||g.ab("Edge")||g.ab("Silk")||g.ab("Android"))&&!(g.wd()||g.ab("iPad")||g.ab("iPod"));var Xd={},Haa=0,Nba=g.p("yt.net.ping.workerUrl_")||null;g.m("yt.net.ping.workerUrl_",Nba,void 0);g.Yd.prototype.Rb=g.ba(2);g.Zd.prototype.toString=function(){return this.topic};var Oba=g.p("yt.pubsub2.instance_")||new g.tb;g.tb.prototype.subscribe=g.tb.prototype.subscribe;g.tb.prototype.unsubscribeByKey=g.tb.prototype.td;g.tb.prototype.publish=g.tb.prototype.qa;g.tb.prototype.clear=g.tb.prototype.clear;g.m("yt.pubsub2.instance_",Oba,void 0);g.Lh=g.p("yt.pubsub2.subscribedKeys_")||{};g.m("yt.pubsub2.subscribedKeys_",g.Lh,void 0);g.Mh=g.p("yt.pubsub2.topicToKeys_")||{};g.m("yt.pubsub2.topicToKeys_",g.Mh,void 0);g.Nh=g.p("yt.pubsub2.isAsync_")||{};
g.m("yt.pubsub2.isAsync_",g.Nh,void 0);g.m("yt.pubsub2.skipSubKey_",null,void 0);var me=(0,g.F)().toString();var se=window.performance||window.mozPerformance||window.msPerformance||window.webkitPerformance||{};g.u(be,g.Yd);var Raa=new g.Zd("timing-sent",be);var Iaa=/url\(["']?(http[^'"\)]+)['"]?\)/i;var ve={'script[name="scheduler/scheduler"]':"sj",'script[name="player/base"]':"pj",'link[rel="stylesheet"][name="www-player"]':"pc",'script[name="desktop_polymer/desktop_polymer"]':"dpj",'link[rel="import"][name="desktop_polymer"]':"dph",'script[name="mobile_polymer/mobile_polymer"]':"mpj",'link[rel="import"][name="mobile_polymer"]':"mph",'script[name="mobile-polymer-player/mobile-polymer-player"]':"mppj",'link[rel="stylesheet"][name="mobile-polymer-player"]':"mppc"},Oaa=(0,g.q)(se.clearResourceTimings||
se.webkitClearResourceTimings||se.mozClearResourceTimings||se.msClearResourceTimings||se.oClearResourceTimings||g.ea,se),ie=se.mark?function(a){se.mark(a)}:g.ea;g.Pba=g.Md?"webkit":g.df?"moz":g.E?"ms":g.ef?"o":"";g.Oh=g.p("yt.dom.getNextId_");if(!g.Oh){g.Oh=function(){return++Qba};
g.m("yt.dom.getNextId_",g.Oh,void 0);var Qba=0};g.Ee.prototype.preventDefault=function(){this.event&&(this.event.returnValue=!1,this.event.preventDefault&&this.event.preventDefault())};
g.Ee.prototype.stopPropagation=function(){this.event&&(this.event.cancelBubble=!0,this.event.stopPropagation&&this.event.stopPropagation())};
g.Ee.prototype.stopImmediatePropagation=function(){this.event&&(this.event.cancelBubble=!0,this.event.stopImmediatePropagation&&this.event.stopImmediatePropagation())};
var Saa={stopImmediatePropagation:1,stopPropagation:1,preventMouseEvent:1,preventManipulation:1,preventDefault:1,layerX:1,layerY:1,scale:1,rotation:1,webkitMovementX:1,webkitMovementY:1};g.Fe=g.p("yt.events.listeners_")||{};g.m("yt.events.listeners_",g.Fe,void 0);var He=g.p("yt.events.counter_")||{count:0};g.m("yt.events.counter_",He,void 0);var Taa={enablejsapi:1},Uaa={},Vaa={allowscriptaccess:"always",allowfullscreen:"true",bgcolor:"#000000"};Ne.prototype.clone=function(){var a=new Ne,b;for(b in this)if(this.hasOwnProperty(b)){var c=this[b];"object"==g.ga(c)?a[b]=g.Xa(c):a[b]=c}return a};g.Pe=null;g.Ue=/\s*;\s*/;g.h=g.Te.prototype;g.h.isEnabled=function(){return window.navigator.cookieEnabled};
g.h.set=function(a,b,c,d,e,f){if(/[;=\s]/.test(a))throw Error('Invalid cookie name "'+a+'"');if(/[;\r\n]/.test(b))throw Error('Invalid cookie value "'+b+'"');g.ca(c)||(c=-1);e=e?";domain="+e:"";d=d?";path="+d:"";f=f?";secure":"";c=0>c?"":0==c?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date((0,g.F)()+1E3*c)).toUTCString();this.A.cookie=a+"="+b+e+d+c+f};
g.h.get=function(a,b){for(var c=a+"=",d=(this.A.cookie||"").split(g.Ue),e=0,f;f=d[e];e++){if(0==f.lastIndexOf(c,0))return f.substr(c.length);if(f==a)return""}return b};
g.h.remove=function(a,b,c){var d=g.ca(this.get(a));this.set(a,"",0,b,c);return d};
g.h.Lb=g.ba(3);g.h.kb=g.ba(4);g.h.isEmpty=function(){return!this.A.cookie};
g.h.pb=g.ba(0);g.h.ne=g.ba(5);g.h.clear=function(){for(var a=g.Ve(this).keys,b=a.length-1;0<=b;b--)this.remove(a[b])};
g.We=new g.Te("undefined"==typeof window.document?null:window.document);g.We.C=3950;g.Ph=g.E?"focusin":"DOMFocusIn";g.Qh=g.E?"focusout":"DOMFocusOut";g.Rh=g.Md?"webkitTransitionEnd":g.ef?"otransitionend":"transitionend";g.h=g.hf.prototype;g.h.getHeight=function(){return this.bottom-this.top};
g.h.clone=function(){return new g.hf(this.top,this.right,this.bottom,this.left)};
g.h.contains=function(a){return g.jf(this,a)};
g.h.ceil=function(){this.top=Math.ceil(this.top);this.right=Math.ceil(this.right);this.bottom=Math.ceil(this.bottom);this.left=Math.ceil(this.left);return this};
g.h.floor=function(){this.top=Math.floor(this.top);this.right=Math.floor(this.right);this.bottom=Math.floor(this.bottom);this.left=Math.floor(this.left);return this};
g.h.round=function(){this.top=Math.round(this.top);this.right=Math.round(this.right);this.bottom=Math.round(this.bottom);this.left=Math.round(this.left);return this};
g.h.scale=function(a,b){var c=g.ka(b)?b:a;this.left*=a;this.right*=a;this.top*=c;this.bottom*=c;return this};g.h=g.kf.prototype;g.h.clone=function(){return new g.kf(this.left,this.top,this.width,this.height)};
g.h.contains=function(a){return a instanceof g.kf?this.left<=a.left&&this.left+this.width>=a.left+a.width&&this.top<=a.top&&this.top+this.height>=a.top+a.height:a.x>=this.left&&a.x<=this.left+this.width&&a.y>=this.top&&a.y<=this.top+this.height};
g.h.ceil=function(){this.left=Math.ceil(this.left);this.top=Math.ceil(this.top);this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};
g.h.floor=function(){this.left=Math.floor(this.left);this.top=Math.floor(this.top);this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};
g.h.round=function(){this.left=Math.round(this.left);this.top=Math.round(this.top);this.width=Math.round(this.width);this.height=Math.round(this.height);return this};
g.h.scale=function(a,b){var c=g.ka(b)?b:a;this.left*=a;this.width*=a;this.top*=c;this.height*=c;return this};var lf;lf={};g.Sh=g.df?"MozUserSelect":g.Md||g.yh?"WebkitUserSelect":null;g.fa(g.tf);g.sf=g.p("yt.prefs.UserPrefs.prefs_")||{};g.m("yt.prefs.UserPrefs.prefs_",g.sf,void 0);g.h=g.tf.prototype;g.h.get=function(a,b){vf(a);uf(a);var c=void 0!==g.sf[a]?g.sf[a].toString():null;return null!=c?c:b?b:""};
g.h.set=function(a,b){vf(a);uf(a);if(null==b)throw"ExpectedNotNull";g.sf[a]=b.toString()};
g.h.remove=function(a){vf(a);uf(a);delete g.sf[a]};
g.h.save=function(){var a;a=[];for(var b in g.sf)a.push(b+"="+(0,window.escape)(g.sf[b]));a=a.join("&");g.Xe("PREF",a,63072E3)};
g.h.clear=function(){g.sf={}};g.Th=g.Qa(function(){if(g.E)return g.Ad("10.0");var a=window.document.createElement("DIV"),b=g.gf(),c={transition:"opacity 1s linear"};b&&(c[b+"-transition"]="opacity 1s linear");g.yc(a,g.wc("div",{style:c}));return""!=g.nf(a.firstChild,"transition")});g.fa(g.Cf);g.Cf.prototype.getVersion=function(){return[this.major,this.minor,this.A]};var Zaa=/cssbin\/(?:debug-)?([a-zA-Z0-9_-]+?)(?:-2x|-web|-rtl|-vfl|.css)/;var $f;var Uh=g.$a,Uh=Uh.toLowerCase();if(g.ya(Uh,"android")){var Vh=Uh.match(/android\D*(\d\.\d)[^\;|\)]*[\;\)]/);if(Vh)$f=Number(Vh[1]);else{var Wh={cupcake:1.5,donut:1.6,eclair:2,froyo:2.2,gingerbread:2.3,honeycomb:3,"ice cream sandwich":4,jellybean:4.1},Xh=Uh.match("("+g.Sa(Wh).join("|")+")");$f=Xh?Wh[Xh[0]]:0}}else $f=void 0;var bba=['video/mp4; codecs="avc1.42001E, mp4a.40.2"','video/webm; codecs="vp8.0, vorbis"'],cba=['audio/mp4; codecs="mp4a.40.2"'];g.u(g.Nf,g.pb);g.Nf.prototype.Va=g.ba(6);g.Nf.prototype.S=function(){Pf(this);g.Nf.K.S.call(this)};var $aa={"api.invalidparam":2,auth:150,"drm.auth":150,heartbeat:150,"html5.unsupportedads":5,"fmt.noneavailable":5,"fmt.decode":5,"fmt.unplayable":5,"html5.missingapi":5,"html5.unsupportedlive":5,"drm.unavailable":5};g.u(Sf,g.pb);var aba=["drm.unavailable","fmt.noneavailable","html5.missingapi","html5.unsupportedads","html5.unsupportedlive"];g.h=Sf.prototype;g.h.getId=function(){return this.ia};
g.h.xo=function(a,b){this.isDisposed()||(Uf(this,a),Yf(this,b),this.L&&Vf(this))};
g.h.az=function(){return this.lb};
g.h.pO=function(){if(!this.aa){var a=ag(this);a&&"html5"==cg(this)?(this.F="html5",this.L||this.Qg()):(dg(this),this.F="html5",a&&this.M?(this.D.appendChild(this.M),this.Qg()):(this.A.loaded=!0,this.R=(0,g.q)(function(){var a=this.D,c=this.A.clone();g.p("yt.player.Application.create")(a,c);this.Qg()},this),this.aa=!0,a?this.R():(g.Ec(this.A.assets.js,this.R),g.Mf(this.A.assets.css))))}};
g.h.oO=function(){var a=this.A.clone();if(!this.G){var b=Xf(this);b&&(this.G=window.document.createElement("span"),this.G.tabIndex=0,Of(this.ga,this.G,"focus",this.Bt),this.W=window.document.createElement("span"),this.W.tabIndex=0,Of(this.ga,this.W,"focus",this.Bt),g.Rd(this.G,b),g.Sd(this.W,b))}a.attrs.width=a.attrs.width||"100%";a.attrs.height=a.attrs.height||"100%";"flash"==cg(this)?(this.F="flash",this.L||Lf(a,!1,(0,g.q)(this.Qg,this))):(dg(this),this.F="flash",this.A.loaded=!0,g.Kf(this.D,a),
this.Qg())};
g.h.Bt=function(){Xf(this).focus()};
g.h.Qg=function(){if(!this.isDisposed()){var a=Xf(this),b=!1;try{a&&a.getApiInterface&&a.getApiInterface()&&(b=!0)}catch(f){}if(b)if(this.aa=!1,a.isNotServable&&a.isNotServable(this.A.args.video_id))Zf(this);else{Qf(this);this.L=!0;a=Xf(this);a.addEventListener&&(this.T=bg(this,a,"addEventListener"));a.removeEventListener&&(this.Qa=bg(this,a,"removeEventListener"));for(var b=a.getApiInterface(),b=b.concat(a.getInternalApiInterface()),c=0;c<b.length;c++){var d=b[c];this.api[d]||(this.api[d]=bg(this,
a,d))}for(var e in this.B)this.T(e,this.B[e]);Vf(this);this.Xa&&this.Xa(this.api);this.Y.qa("onReady",this.api)}else this.Hb=g.yb((0,g.q)(this.Qg,this),50)}};
g.h.EO=function(){return this.L};
g.h.ge=function(a,b){if(!this.isDisposed()){var c=Tf(this,b);if(c){if(!g.Ka(this.gc,a)&&!this.B[a]){var d=dba(this,a);this.T&&this.T(a,d)}this.Y.subscribe(a,c);"onReady"==a&&this.L&&g.yb(g.r(c,this.api),0)}}};
g.h.vM=function(a,b){if(!this.isDisposed()){var c=Tf(this,b);c&&this.Y.unsubscribe(a,c)}};
g.h.ey=function(a){a=a?Faa:Eaa;for(var b=a(window.document.activeElement);b&&(1!=b.nodeType||b==this.G||b==this.W||(b.focus(),b!=window.document.activeElement));)b=a(b)};
g.h.Yo=function(a){g.z("a11y-announce",a)};
g.h.xI=function(a){Zf(this,a)};
g.h.AI=function(a){g.z("WATCH_LATER_VIDEO_ADDED",a)};
g.h.BI=function(a){g.z("WATCH_LATER_VIDEO_REMOVED",a)};
g.h.hI=function(){this.hb||(g.Jh?(this.bb=g.Ld(window.document),Of(this.H,window,"scroll",this.FK),Of(this.H,this.D,"touchmove",this.nK)):(Of(this.H,this.D,"mousewheel",this.Ot),Of(this.H,this.D,"wheel",this.Ot)),this.hb=!0)};
g.h.iI=function(){Pf(this.H);this.hb=!1};
g.h.Ot=function(a){g.Je(a)};
g.h.FK=function(){window.scrollTo(this.bb.x,this.bb.y)};
g.h.nK=function(a){a.preventDefault()};
g.h.qO=function(){dg(this);this.F="unsupported";var a='Adobe Flash Player or an HTML5 supported browser is required for video playback. <br> <a href="http://get.adobe.com/flashplayer/">Get the latest Flash Player</a> <br> <a href="/html5">Learn more about upgrading to an HTML5 browser</a>',b=window.navigator.userAgent.match(/Version\/(\d).*Safari/);b&&5<=(0,window.parseInt)(b[1],10)&&(a='Adobe Flash Player or QuickTime is required for video playback. <br> <a href="http://get.adobe.com/flashplayer/"> Get the latest Flash Player</a> <br> <a href="http://www.apple.com/quicktime/download/">Get the latest version of QuickTime</a>');
b=this.A.messages.player_fallback||a;a=g.C("player-unavailable");g.C("unavailable-submessage")&&a&&(g.C("unavailable-submessage").innerHTML=b,(b=g.D("icon",a))&&g.Bc(b,"icon")&&(b.src=g.A(b,"icon")),g.rf(a,!0),g.I(g.C("player"),"off-screen-trigger"))};
g.h.Sz=function(){return this.F||cg(this)};
g.h.Dz=function(){return this.sb};
g.h.cancel=function(){this.R&&g.Fc(this.A.assets.js,this.R);g.Ab(this.Hb);this.aa=!1};
g.h.S=function(){dg(this);if(this.M&&this.A)try{this.M.destroy()}catch(b){g.Cb(b)}this.Za=null;for(var a in this.B)g.da[this.B[a]]=null;this.lb=this.A=this.api=null;delete this.D;delete this.O;Sf.K.S.call(this)};g.fg={};g.eg="player_uid_"+(1E9*Math.random()>>>0);var Rba=g.p("yt.abuse.botguardInitialized")||Qe;g.m("yt.abuse.botguardInitialized",Rba,void 0);var Sba=g.p("yt.abuse.invokeBotguard")||g.Re;g.m("yt.abuse.invokeBotguard",Sba,void 0);var Tba=g.p("yt.abuse.dclkstatus.checkDclkStatus")||Se;g.m("yt.abuse.dclkstatus.checkDclkStatus",Tba,void 0);var Uba=g.p("yt.player.exports.navigate")||g.cf;g.m("yt.player.exports.navigate",Uba,void 0);var Vba=g.p("yt.player.embed")||g.gg;g.m("yt.player.embed",Vba,void 0);var Wba=g.p("yt.player.getPlayerByElement")||g.hg;
g.m("yt.player.getPlayerByElement",Wba,void 0);var Xba=g.p("yt.util.activity.init")||g.Le;g.m("yt.util.activity.init",Xba,void 0);var Yba=g.p("yt.util.activity.getTimeSinceActive")||g.Me;g.m("yt.util.activity.getTimeSinceActive",Yba,void 0);var Zba=g.p("yt.util.activity.setTimestamp")||Ke;g.m("yt.util.activity.setTimestamp",Zba,void 0);var kg,pg;g.og=null;pg="";ug.prototype.reset=function(){this.context=this.C=this.D=this.A=null;this.B=!1};
var vg=new eb(function(){return new ug},function(a){a.reset()},100);
g.tg.prototype.then=function(a,b,c){return g.Fg(this,g.ma(a)?a:null,g.ma(b)?b:null,c)};
g.qg(g.tg);g.tg.prototype.cancel=function(a){0==this.A&&mb(function(){var b=new Eg(a);zg(this,b)},this)};
g.tg.prototype.W=function(a){this.A=0;g.sg(this,2,a)};
g.tg.prototype.H=function(a){this.A=0;g.sg(this,3,a)};
g.tg.prototype.O=function(){for(var a=null;a=Ag(this);)Bg(this,a,this.A,this.L);this.G=!1};
var Hg=db;g.u(Eg,g.ra);Eg.prototype.name="cancel";var Ig=[];var Mg=[];var Qg,gh,fh,Sg,Rg,vba,oba,rba,pba,qba,bh;Sg=0;Rg=0;vba=["server_prefetched_vast","vmap"];oba=[900,60,"waiting"];rba=[500,99,"waiting"];pba=[300,60,"waiting"];qba=[400,99,"waiting"];bh=[300,101,"done"];window.yt=window.yt||{};g.m("yt.setConfig",g.wb,void 0);g.m("yt.getConfig",g.v,void 0);g.m("yt.hasMsg",g.Eb,void 0);g.m("yt.pubsub.publish",g.z,void 0);g.m("yt.pubsub.subscribe",g.x,void 0);g.m("yt.setMsg",function(a){ub(g.Db,arguments)},void 0);
g.m("yt.setGoogMsg",function(a){ub(g.Db,arguments)},void 0);
g.m("yt.timing.reportAdToVideo",function(a,b,c){c={v:2,s:"youtube",action:c?"watch,ad2video_html5":"watch,ad2video"};a.aft=a.pbs=a.astv||a.actv;var d=[],e;for(e in a)"_"!=e.charAt(0)&&d.push(e+"."+Math.round(a[e]));c.rt=d.join(",");for(var f in b)"_"!=f.charAt(0)&&(c[f]=b[f]);a=g.v("TIMING_INFO",{});"e"in a&&(c.e=a.e);"ei"in a&&(c.ei=a.ei);ue(c)},void 0);
g.m("ytcsi.tick",g.ke,void 0);g.u(hh,g.Tb);
hh.prototype.enable=function(){window.onload=mba;window.onunload=nba;window.onerror=naa;var a=window.ytspf||{};a.enabled?(window.addEventListener&&(window.addEventListener("spfclick",Og),window.addEventListener("spfhistory",Pg),window.addEventListener("spfrequest",Ug),window.addEventListener("spfpartprocess",Yg),window.addEventListener("spfpartdone",Zg),window.addEventListener("spfprocess",$g),window.addEventListener("spfdone",ch),window.addEventListener("spferror",dh),window.addEventListener("spfreload",
eh),window.addEventListener("spfjsbeforeunload",ih)),a.config=a.config||{},window.ytdepmap?window.spf.script.ready("spf",function(){a.enabled=window.spf.init(a.config)}):a.enabled=window.spf.init(a.config),this.subscribe("init",tba),this.subscribe("dispose",uba)):window.spf.dispose();
this.subscribe("init",this.init,this);this.subscribe("dispose",this.dispose,this)};
hh.prototype.init=function(){hh.K.init.call(this);(window.ytspf||{}).enabled||window.spf.dispose();var a=window.ytPageFrameLoaded||!1,b,c;!a&&g.v("PAGEFRAME_JS")?(b=g.v("PAGEFRAME_JS",void 0),c=function(){window.ytPageFrameLoaded=!0;g.p("ytbin.www.pageframe.setup")()}):a&&(a=g.p("yt.www.masthead.loadSearchbox"))&&a();
var a=g.v("JS_COMMON_MODULE"),d=g.v("JS_PAGE_MODULES");d||(d=[a]);a=g.v("JS_DELAY_LOAD",0);0<a?(g.Ab(this.B),this.B=g.yb(function(){b&&g.Ec(b,c);window.spf.script.require(d)},a)):(b&&g.Ec(b,c),window.spf.script.require(d));
fba();g.m("yt.timing.ready_",!0,void 0);Paa();Naa();je(!1)};
hh.prototype.dispose=function(){g.Ab(this.B);var a=g.p("ytbin.www.pageframe.cancelSetup");a&&a();g.Bb(kg);if(a=g.mg())a.removeEventListener("onReady",lg),a.removeEventListener("onStateChange",lg);g.m("yt.timing.ready_",!1,void 0);hh.K.dispose.call(this)};
hh.prototype.disable=function(){hh.K.disable.call(this);window.removeEventListener&&(window.removeEventListener("spfclick",Og),window.removeEventListener("spfhistory",Pg),window.removeEventListener("spfrequest",Ug),window.removeEventListener("spfpartprocess",Yg),window.removeEventListener("spfpartdone",Zg),window.removeEventListener("spfprocess",$g),window.removeEventListener("spfdone",ch),window.removeEventListener("spferror",dh),window.removeEventListener("spfreload",eh),window.removeEventListener("spfjsbeforeunload",
ih));window.onload=null;window.onunload=null;window.onerror=null};
g.Yb(new hh);})(_yt_www);
